### ISSUE TITLE
能否在一个规则内添加多个排除

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/HeaderEditor#10]
由 #2 引发。
正则虽然能写，但数量多了以后就很难维护了。
如果分多条规则写也是很麻烦的事情。

**Comment by sylingd** [comment]
正在编写中的自定义函数可以解决此问题

**Comment by ivysrono** [comment]
不好意思，实在是不怎么会JS，只好请教下，怎么用自定义函数实现如下需求：
响应头：Content-Security-Policy 插入头内容：upgrade-insecure-requests
排除：
a.com
b.cn
c.info
d.com/efg
(?!www).h.com/.+
……

**Comment by sylingd** [comment]
目前自定义函数功能功能还不足够，增强正在计划中

**Comment by sylingd** [comment]
例如，下面规则会给所有域名包含baidu，但不包含example.com（即对baidu.demo.com、baidu.org生效），修改User-Agent头：
```
const domain = /.*?:\/*([^\/:]+)/.exec(detail.url)[1];
if (!domain.includes('baidu') || domain.includes('example.com')) {
return;
}
for (let a in val) {
	if (val[a].name.toLowerCase() === 'user-agent') {
		val[a].value += ' HE/2.0.0';
		break;
	}
}
```

**Comment by ivysrono** [comment]
2.3.0就行？还是要等新版？

**Comment by sylingd** [comment]
2.3.0

**Comment by ivysrono** [comment]
不成功，烦请指导。
![default](https://user-images.githubusercontent.com/2649544/30771825-6059de10-a082-11e7-9ac9-afcad9df1192.png)

```
const domain = /.*?:\/*([^\/:]+)/.exec(detail.url)[1];
if (!domain.includes('lofter.com') || domain.includes('cmbchina.com')) {
return;
}
for (let a in val) {
	if (val[a].name.toLowerCase() === 'Content-Security-Policy') {
		val[a].value += ' upgrade-insecure-requests';
		break;
	}
}

```

**Comment by sylingd** [comment]
使用了toLowerCase，请使用小写英文字母作比较

**Comment by ivysrono** [comment]
thanks.
但我测试结果，还是不符合我的需求。我是希望在所有 https 页面生效，仅排除个别域名或网址。

`if (!domain.includes('1') || domain.includes('2'))`

这个语句如何替换 1 实现全页面生效？

而且下面这句貌似无效：
```
const domain = /.*?:\/*([^\/:]+)/.exec(detail.url)[1];
if (!domain.includes('cmbchina.com') || domain.includes('hk.cmbchina.com')) {
return;
}
for (let a in val) {
	if (val[a].name.toLowerCase() === 'content-security-policy') {
		val[a].value += ' upgrade-insecure-requests';
		break;
	}
}
```

**Comment by sylingd** [comment]
```
const domain = /.*?:\/*([^\/:]+)/.exec(detail.url)[1];
```
这行代码会提取出URL的域名部分，例如`https://github.com/FirefoxBar/HeaderEditor/issues/10`的提取结果是`github.com`
下面使用的是includes方法作判断，这是关于`includes`方法的说明：[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/includes)
类似的方法还有indexOf等，详情请在MDN查看
