### ISSUE TITLE
修改请求头 $1 占用符无效

### ISSUE THREAD

**Issue by PetTko** [FirefoxBar/HeaderEditor#100]
上几个版本就出现了，之前没问题，例：

> `.*\/\/(.*?)\/.*\?url=(.*?)`
> referer
> `$1\/\?url=$2`

**Comment by sylingd** [comment]
1. 斜杠（/）不需要转义
2. 这条规则执行后，地址将会变成不带HTTP的。此时地址无效
3. 替换结果不需要转义
4. 以“.*”开头的规则可能会卡死Firefox
5. 经过测试，如下面规则是可以正常运行的（效果：将`http://example.com/demo.php?url=some_url`重定向至`http://example.com/?url=some_url`）：
![image](https://user-images.githubusercontent.com/5326684/47618073-b4d75680-db09-11e8-83ce-9b07855a0ae4.png)

**Comment by sylingd** [comment]
另外，修改请求头从来没有支持过占位符

**Comment by PetTko** [comment]
> 另外，修改请求头从来没有支持过占位符

感谢回复，老版本修改请求头支持占位符，应是修改 UI 后不可用？还请确认一下，谢谢。

**Comment by sylingd** [comment]
老版本从来没有支持过。有这类需求的请使用自定义函数
