### ISSUE TITLE
Edit for imported rules does not work

### ISSUE THREAD

**Issue by crssi** [FirefoxBar/HeaderEditor#101]
Firefox: 63 x64
Header Editor: 4.0.2
OS: Windows 10 x64
Addons: New profile with HE only

When rules are imported (`Options -> Export and Import -> Download rule`), then we cannot edit those rules anymore.

Additionally when clicked `Edit` button on one of imported rules (nothing happens) and after we click `+` the new rule is partially filled with data of the rules we prior clicked the `Edit` button.

Edit: Also when `Clone` is used, the new rule does not "happen".

Cheers

**Comment by sylingd** [comment]
I have tested on firefox nightly and chrome, it works well. Please take a screenshot of Console (Press F12), maybe it is helpful.

**Comment by crssi** [comment]
When I click edit on FF63 nothing happens and the console throws out this:
```
TypeError: e.action is undefined[Learn More]      options.js:38:101620
onEditRule      moz-extension://addon_id/options/options.js:38:101620
onEditRule      self-hosted:974:17
click      moz-extension://addon_id/options/options.js:38:114665
t      moz-extension://addon_id/options/options.js:7:12128
sr/t</e._withTask      moz-extension://addon_id/options/options.js:7:41323
```

In upper text I have replaced long AddonID with `addon_id`.

Do you need a screenshot or upper info is good enough?

Cheers

**Comment by sylingd** [comment]
It seems that this problem is related to the rules you imported. Can you give me the rules you imported?

**Comment by crssi** [comment]
Sure... here they are: `https://raw.githubusercontent.com/crssi/Firefox/master/HeaderEditor.json`

Thank you

**Comment by sylingd** [comment]
The Header Editor has some problems dealing with custom functions, I have fixed them and will take effect in the next version

**Comment by crssi** [comment]
You are best :+1:, thank you.
Please close this issue when appropriate for you.

Cheers

**Comment by sylingd** [comment]
Thank you for your feedback

**Comment by sylingd** [comment]
I have released 4.0.3, please update to test

**Comment by crssi** [comment]
Thank you. Will do, but I am back to real
Internet access after 6th november. 

Cheers

**Comment by crssi** [comment]
It seems to be working now as intended.

Thank you @sylingd :smile:
