### ISSUE TITLE
Aditional functionality request

### ISSUE THREAD

**Issue by crssi** [FirefoxBar/HeaderEditor#107]
Dear @sylingd 

Is there any chance that you would add the function that could be used in "custom function" which will return domain match on SLD (second level domain), actually full functionality of the following function:
[https://github.com/wrangr/psl](https://github.com/wrangr/psl).

I have a need to remove or modify some request and/or response header where SLD match or does not match the header value data.

For example I would like to strip Origin header, but only if SLD of the Origin header does not match URL:
request made to amazon.co.uk with Origin amazon.com would not be modified.

If my request isn't clear, let me know and I will try to write it more clearly.

Thank you and cheers

**Comment by sylingd** [comment]
You can use "detail" object, but you should detect SLD by your se;f.

For example:

```javascript
// If url contains amazon.co.uk, we will do nothing about this request
if (!detail.url.includes('amazon.co.uk')) {
	return;
}
for (const a of val) {
	// we only modify origin header when it contains amazon.com
	if (a.name.toLowerCase() === 'origin' && a.value.includes('amazon.com')) {
		a.value = a.value.replace('amazon.com', 'example.com');
		break;
	}
}
```

In the example above, I use "includes" to make a simple check, it is simple and fast, but it's not accurate. If you need more precise checks, you may need to write a regular expressions or more javascript codes.

**Comment by crssi** [comment]
Thank you for your fast response, as always.

I somehow knew I wasn't clear.
The "amazon" was just as an a single example.
There are many such requests all over the Internet. And I would need something more general.
There is also a host part of URL which should also be ignored as a match at this kind of a request, like:
host.somedomain.tld is match to xyz.somedomain.* (TLD = Top Level Domain).

If we use the [https://github.com/wrangr/psl](https://github.com/wrangr/psl) (see [example](https://github.com/wrangr/psl#example)) the upper is simply achieved with something like this:

detail.url value is for example: www.google.co.uk
origin header has for example a value: application.google.com
in this case we have a SLD match

OK, we need to strip out schema and path from detail.url (upper is a bit simplified for explanation).

``` js
for (const header of val) {
	if (header.name.toLowerCase() === 'origin') {
		// if sld match then return without modifying
		if ((psl.parse(detail.url)).sld == (psl.parse(header.value)).sld) { return; }
		// if sld does not match then modify the header origin value
		header.value = detail.url.split('/', 3).join('/');
		return;
	}
}
```
Cheers

**Comment by sylingd** [comment]
You may need to implement a function to resolves the SLD.

You can found all SLD at psl repo data/rules.json

For example:

```javascript
const findSld = (d) => {
	const rules = ["ac", "com.ac", "edu.ac", "gov.ac", "net.ac", "cn"]; // All SLDs
	for (const r of rules) {
		if (d.endsWith('.' + r)) {
			const m = d.substr(0, d.length - r.length - 1);
			return m.substr(m.lastIndexOf('.') + 1);
		}
	}
	// Unlisted tld
	const m = d.substr(0, d.lastIndexOf('.'));
	return m.substr(m.lastIndexOf('.') + 1);
};
const findDomain = (u) => {
	return /.*?:\/*([^\/:]+)/.exec(u)[1];
};
const domain = findDomain(detail.url);
const urlSld = findSld(domain);

for (const header of val) {
	if (header.name.toLowerCase() === 'origin') {
		// if sld match
		if (urlSld === findSld(findDomain(header.value))) {
			return;
		}
		// if sld does not match
		header.value = detail.url.split('/', 3).join('/');
		return;
	}
}
```

But please note that complex custom functions may make requests slow.

**Comment by crssi** [comment]
Thank you, that was very nice of you. :heart: 

> But please note that complex custom functions may make requests slow.

I tough so too, so I assumed that if this would be implemented in your extension, that it would be more efficient.

**Comment by crssi** [comment]
OMG, you are THE MAN. :smile: 
Yesterday I haven't had time to test your suggested script, which I have now and with full TLDs json list.
I works like a charm and I do not see some real culprits about being slow... at lest not from user perspective.
But its also true that I have a higher end of CPU here, so I will try the same also on a low end CPU computer.

Cheers

**Comment by sylingd** [comment]
I dont know the custom function will be optimized by the JS engine or not – I guess will. But it might be better to write another extension to implement some complex features.

**Comment by crssi** [comment]
I understand completely.
I really appreciate your help and thank you.

Should I close this "issue"?

Cheers

**Comment by sylingd** [comment]
Thank you for your support
