### ISSUE TITLE
请问有日志文件可以查阅吗？

### ISSUE THREAD

**Issue by waldens** [FirefoxBar/HeaderEditor#109]
百分浏览器版本 3.6.8.99（正式版本） （64 位） (portable) (Chromium 69.0.3497.100)

总是提示我错误
> uBlock Origin
 此扩展程序无法将该网络请求重新定向到 chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/f1df24e1f123b1137cec098dab038b34.js?secret=tro6cqzyo42f，因为其他扩展程序（Header Editor）已将其重新定向到 https://www.google.com/tag/js/gpt.js。

> uBlock Origin
此扩展程序无法将该网络请求重新定向到 chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/59fb24a2d12455d15bea20980e8a6801.js?secret=skh74sv550eq，因为其他扩展程序（Header Editor）已将其重新定向到 https://www.google.com/analytics.js。

但是我HeaderEditor里的规则太多了，没办法轻易用二分查找、启用禁用规则，来定位是哪一条规则的问题。如果有个日志文件，能记录，基于哪条规则把哪个URL重定向到哪个URL，这样就好定位了

不知道有吗？

**Comment by sylingd** [comment]
没有，目前只能通过批量禁用来排查

**Comment by sylingd** [comment]
另外推测应该是和Google相关的规则，如跳转HTTPS等

**Comment by waldens** [comment]
谢谢，确实是google相关规则，已解决
