### ISSUE TITLE
火狐不接受Cookie时无法新建规则

### ISSUE THREAD

**Issue by sakuyaa** [FirefoxBar/HeaderEditor#11]
火狐55.0.3 64位Win，新建配置，在选项中取消勾选`接受来自站点的Cookie`（即network.cookie.cookieBehavior的值设为2）。
安装扩展1.1.0版本后工具栏按钮无反应，从附加组件管理器中该扩展选项可以进入管理界面，但是点击添加规则保存后浏览器控制台提示`Error: Could not establish connection. Receiving end does not exist.`
很奇怪的一个Bug，怀疑是出现在saveRule函数里，不过我还不懂IndexedDB，找不出问题所在呢

**Comment by sylingd** [comment]
这是Firefox的BUG。此扩展使用IndexedDB储存相关规则。但禁止Cookie时，IndexedDB也无法读写。
类似问题可以参见：[Stylus #152](https://github.com/openstyles/stylus/issues/152)

**Comment by sylingd** [comment]
这是Firefox的BUG。此扩展使用IndexedDB储存相关规则。但禁止Cookie时，IndexedDB也无法读写。
类似问题见：[Stylus 152](http://dwz.cn/6tno2M) [Stylus 170](http://dwz.cn/6tnnMJ)

**Comment by sakuyaa** [comment]
看了一会目前只能根据[Stylus 170](https://github.com/openstyles/stylus/pull/170)里面说的，自行添加扩展Manifest URL为允许Cookie可以解决。
这个问题在[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1389951)有提到过，但是好像没有提供测试代码被标为INVALID了，感觉这个Bug直到被修复还得等好久。
