### ISSUE TITLE
Master switch in popup is backwards

### ISSUE THREAD

**Issue by vertigo220** [FirefoxBar/HeaderEditor#113]
This is a minor issue, and once it's figured out it's not really a big deal, but the "Disable all" master switch in the popup is backwards IMO. In fact, at first it caused me to disable all my rules by accident because the fact the switch was to the left and grayed out made it look like HE was off and all rules were disabled, whereas "flipping" the switch and making it turn blue made it look like HE was on and the rules were enabled. It would make more sense to be the other way around (rules disabled when switch is left and grayed and enabled when switch is right and blue), with either "Disable all" changed to something like "Enabled" or "Disabled," which would change based on the state. Another option would be to make it a button instead, in case for some reason the switch being the other way around wouldn't make sense for some users. Then the text would just change to indicate the present state (or it could just be a power button without text), maybe with the button being blue or green when enabled and white or red when disabled).

**Comment by sylingd** [comment]
Good advice, I will consider it
