### ISSUE TITLE
Custom function notifications

### ISSUE THREAD

**Issue by Ivan08** [FirefoxBar/HeaderEditor#115]
Can I add notifications or custom page content to the custom function? For example, if there is a defined header, create a notification near the extension icon in the browser panel, or add arbitrary text to the page?

**Comment by sylingd** [comment]
You can use all webextension api,  see here: [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)

**Comment by sylingd** [comment]
You may use the following APIs:
* browserAction.setBadgeText
* tabs.executeScript
* Web Notification (not browser.notification API)

**Comment by crssi** [comment]
That idea is really cool. :smile: 
@sylingd do you might have any short example of code?

Thank you and cheers

**Comment by sylingd** [comment]
### Using WebExtension API

It can display a small amount of text on the extension icon.

Not recommended. Although HE does not use this feature at present, it does not mean that it will not be used in the future.

```javascript
chrome.browserAction.setBadgeText({
	text: "Text"
});
```

### Using Web Notification

Before use it, you should open options page of HE, open console (Press F12), then execute `Notification.requestPermission()`.

Next, you can use it like this in your script:

```javascript
new Notification("This is a notification");
```

More documentions, see here: [https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)

**Comment by crssi** [comment]
Thank you, those examples are great.

**Comment by crssi** [comment]
I assume that the first one is not recommended/supported, since HE does not listen for onTabChange and we cant set a tab specific badge, but only general.

**Comment by Ivan08** [comment]
Thanks, setBadgeText works well. But there are problems with the rest.
`Notification.requestPermission ()` needs to be performed on each page separately, which is not very convenient.
browser.tabs.executeScript failed to start, when trying to execute any script in the console, the error "Unable to run script because scripts are blocked internally".
It would be convenient to save a certain log and display it when you click on the extension icon. It would be very convenient and informative.
Or a separate page / popup where you can see this log. For example, the uBlock extension has a separate page with the request log.
