### ISSUE TITLE
Clone function asks for group name instead of rule name

### ISSUE THREAD

**Issue by vertigo220** [FirefoxBar/HeaderEditor#116]
When cloning a rule, the popup says "Please enter a group name" when it's actually asking for a name for the new/cloned rule. It should say "Please enter a rule name" instead.

**Comment by Atavic** [comment]
Maybe there's an issue [here](https://github.com/FirefoxBar/HeaderEditor/blob/70040cda83cb055412bebcb793eda8f214c85558/src/options/App.vue#L701)
