### ISSUE TITLE
Chrome下无法修改referer header

### ISSUE THREAD

**Issue by fireattack** [FirefoxBar/HeaderEditor#117]
Chrome版本：71.0.3578.80 (Official Build) beta (64-bit) (cohort: Beta)

测试方法：添加以下规则：

![image](https://user-images.githubusercontent.com/4130991/49693924-e1a27300-fb77-11e8-98a2-f6cdbb5e44c6.png)

地址：https://nghttp2.org/httpbin/headers
Header name：referer
Header value：http://example.com

然后打开 https://nghttp2.org/httpbin/headers

应该返回referer为 http://example.com ，但是实际并未被修改

在Firefox下同样的规则完全正常

**Comment by sylingd** [comment]
在71.0中测试正常，请检查是否与其他扩展冲突
![image](https://user-images.githubusercontent.com/5326684/49694242-b2185880-fbc1-11e8-8105-af45b0e6a1b2.png)

**Comment by fireattack** [comment]
奇怪，我是用的全新profile测试的，没有其他插件…

**Comment by fireattack** [comment]
请问你使用的是 71.0.3578.80 (Official Build) beta 这个版本吗？还是Stable?

**Comment by sylingd** [comment]
Version 71.0.3578.44 (Official Build) (64-bit)

**Comment by fireattack** [comment]
有点好笑了，同样的版本好Beta版就不行，非Beta版就可以

可以： 

71.0.3578.80 (Official Build) (64-bit) (cohort: 71_Win_80)
--


BUG：


71.0.3578.80 (Official Build) beta (64-bit) (cohort: Beta)
--

**Comment by sylingd** [comment]
我试了一下Beta版，我这里正常的
![tim 20181209170835](https://user-images.githubusercontent.com/5326684/49695413-a5056480-fbd5-11e8-81df-20e014618a3e.png)
![tim 20181209170849](https://user-images.githubusercontent.com/5326684/49695414-a8005500-fbd5-11e8-89c7-e9b1e5aec12c.png)
![tim 20181209170840](https://user-images.githubusercontent.com/5326684/49695415-a9318200-fbd5-11e8-8ab9-b764ea207be3.png)

**Comment by fireattack** [comment]
在 Chromium 的 bug tracker [问了一下](https://bugs.chromium.org/p/chromium/issues/detail?id=913242)，应该是72之后必须加extraHeaders参数后才能修改Referer，但是这个特性在某些A/B test中会适用到71 Beta里，我就中招了。

应该算解决，不过给开发者提个醒，在Chrome 72进入Stable后也要进行相应调整（具体请参见[这里](https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/chromium-extensions/vYIaeezZwfQ/hVln6g1OAgAJ)）。

**Comment by fireattack** [comment]
Chrome 商店还没更新，可以手动下载trunk打包。
