### ISSUE TITLE
[Question]新版本在firefox启动时，图标不会变灰，只有打开再关闭一次才会变灰

### ISSUE THREAD

**Issue by Etisgod** [FirefoxBar/HeaderEditor#124]
Win7 64位
Firefox 60.5.0esr (64 位) 
新版本在firefox启动时，图标不会变灰，只有打开再关闭一次才会变灰
![default](https://user-images.githubusercontent.com/46986061/52515753-af39f280-2c5a-11e9-8141-b3bbb946053d.png)

**Comment by sylingd** [comment]
已修复，感谢反馈
