### ISSUE TITLE
[Question] 请问下重定向针对的是所有内容吗？

### ISSUE THREAD

**Issue by vvyoko** [FirefoxBar/HeaderEditor#125]
比方说我想自定义小图至大图。
但是并不希望在当前网页直接重定向，而是希望拖拽图片在新标签打开时重定向至大图。
如下面一个chrome的扩展类似的选项
扩展名：Redirector
地址：https://chrome.google.com/webstore/detail/redirector/jddedikibcpoigkklkocebdffgplmcle
例子:
[![1.jpg](https://i.loli.net/2019/03/23/5c964199d2a26.jpg)](https://i.loli.net/2019/03/23/5c964199d2a26.jpg)

因 Redirector 年代久远，渐渐跟不上版本了，于是找到了这里
请问下HeaderEditor有针对这种需求的选项吗？

**Comment by vvyoko** [comment]
顺便请问一下
Redirector 分为 匹配 被替换式 替换式
HeaderEditor 把 匹配 和 被替换式 合并成了匹配规则 ，替换式相当于重定向至不说
在正则比较复杂的情况的情况下不会影响性能吗？

比方说 我在Redirector中有个例子，需求就是提取出相关番号
匹配 是 http:\/\/pics\.dmm\.co\.jp.*pl.jpg
被替换式  是 .*\/(.*_?.*\d)?([a-z]{1,6})(00)?([0-9]{3,6})pl.jpg

而在 HeaderEditor 只能在 匹配规则 这样写了
http:\/\/pics\.dmm\.co\.jp.*\/(.*_?.*\d)?([a-z]{1,6})(00)?([0-9]{3,6})pl.jpg
这不会影响性能的吗？

**Comment by vvyoko** [comment]
顺便请问一下
Redirector 分为 匹配 被替换式 替换式
HeaderEditor 把 匹配 和 被替换式 合并成了匹配规则 ，替换式相当于重定向至不说
在正则比较复杂的情况的情况下不会影响性能吗？

比方说 我在Redirector中有个例子，需求就是提取出相关番号
匹配 是 http:\/\/pics\.dmm\.co\.jp.*pl.jpg
被替换式 是 .*\/(.*_?.*\d)?([a-z]{1,6})(00)?([0-9]{3,6})pl.jpg

而在 HeaderEditor 只能在 匹配规则 这样写了
http:\/\/pics\.dmm\.co\.jp.*\/(.*_?.*\d)?([a-z]{1,6})(00)?([0-9]{3,6})pl.jpg
这不会影响性能的吗？

**Comment by sylingd** [comment]
1.使用自定义函数。
2.影响非常小，浏览器会进行JIT编译。当然能用简单的最好还是用简单的

**Comment by vvyoko** [comment]
自定义函数对我还是稍微复杂一点。
照着例子写出来个直接就提示unexpected token
希望帮助一下，比方说只希望在新窗口重定向 google.com 到 baidu.com.该怎么修改。
我在最开始的匹配类型那填了www.google.com，后面的 originUrl 还要填吗？
一些选项比方说 id  , time 都是必选项吗？
照着例子写出来的
`function(val, detail) 
    "id": 123456,
    "url": "www.baidu.com/",
    "method": "POST",
    "isFrame": 0,
    "type": "main_frame",
    "time": 1505613357577.7522,
    "originUrl": "www.google.com"
} `

希望按上面需求给出个修改过的例子，其他的我自己照着去修改就好了。

**Comment by vvyoko** [comment]
自定义函数对我来说还是稍微复杂了一点。例子也稍微硬核了一点。。。
希望给出个只在地址栏重定向google.com 至baidu.com的例子让我去参照着修改会不会有点太伸手党。。
我是真的去试了，完全蒙圈。
我都怀疑我例子都没找对。

function(val, detail) 
    "id": 123456,
    "url": "https://www.baidu.com/",
    "method": "POST",
    "isFrame": 0,
    "type": "main_frame",
    "time": 1505613357577.7522,
    "originUrl": "https://www.google.com"
}

**Comment by sylingd** [comment]
```javascript
if (detail.type === "main_frame") {
	return val.replace('google.com', 'baidu.com');
}
```
![image](https://user-images.githubusercontent.com/5326684/54876449-3332ed00-4e4b-11e9-9764-282fc1666e00.png)

**Comment by vvyoko** [comment]
谢谢，已经全部导入成功了。
开始正则不成功，提示 Unexpected token .说不定也有人像我这样小白在这写下吧。
后面搜索了一下，发现要在正则前后添加 /  后面好像还有 g,ig 的参数，具体我也没找到什么意思 
具体这样写	return val.replace(/正则/, '123');

**Comment by sylingd** [comment]
你可以参见[此处](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp)
