### ISSUE TITLE
[功能需求] 比對可以選擇「來源」或「目標」

### ISSUE THREAD

**Issue by bestpika** [FirefoxBar/HeaderEditor#126]
您好

我現在有個使用情境
我在 inoreader 之類的線上 RSS 閱讀器的圖片需要修改 referer
但是目前匹配的只有「目標」網址
不曉得能不能增加一個選項可以匹配發起 request 的來源？

例如 a.com 包含 b.com 的圖片目前是匹配 b.com，但是希望可以讓我匹配 a.com

謝謝

我知道用自訂函數可以做到這個需求
但是我不確定設定全部的話會不會變成只跑這個規則

**Comment by sylingd** [comment]
您好，我认为大部分情况下，可以直接修改Referer至相应的网址，而不需要关心来源。
例如来自Tumble的图片地址是`https://66.media.tumblr.com/70c0c954ebeaada1322304161299ab7d/tumblr_p46qbo7lDj1rx0figo1_1280.gif`，您可以选择匹配正则表达式，规则为`(.*?).media.tumblr.com`，修改Referer至`https://www.tumblr.com`
如果您确实需要匹配原有的Referer，可以编写如下代码：
```
for (const it of val) {
	if (it.name.toLowerCase() === 'referer') {
		if (it.value.includes('a.com')) {
			// Modify it!
			it.value = 'http://example.com';
		} else {
			// Not from a.com, do something else
		}
	}
}
```

**Comment by bestpika** [comment]
那我另外想問一個問題
關於規則的執行順序

**Comment by sylingd** [comment]
规则的执行顺序是不确定的，不建议依赖于此

**Comment by bestpika** [comment]
那我要想想我要怎樣寫會比較好了
謝謝
