### ISSUE TITLE
[Question] redirect only for single domain?

### ISSUE THREAD

**Issue by atomGit** [FirefoxBar/HeaderEditor#127]
i want to do a redirect, but only for a particular domain - in this case bitchute.com - for example, i want to redirect this...
`https://www.bitchute.com/embed/lZhqPaberPs/`

to this...
`https://www.bitchute.com/video/lZhqPaberPs/`

the RegEx is no problem...
`https:\/\/www\.bitchute\.com\/embed\/([^/]*)\/`
`https://www.bitchute.com/video/$1/`

but how do i preform the redirect only for the bitchute.com domain?

**Comment by sylingd** [comment]
Sorry I can not understand what you means. Could you give me more description? for example, what URLs you want to redirect and what URLs not.

**Comment by atomGit** [comment]
i want to redirect this...
`https:\/\/www\.bitchute\.com\/embed\/([^/]*)\/`

to this...
`https://www.bitchute.com/video/$1/`

the above redirect works, but it works for every domain and i only want it to work for bitchute.com (in other words, only when i have bitchute.com opened in a tab)

**Comment by sylingd** [comment]
Do you means you do not want to redirect requests which is not in a tab (for example, the images, css in webpages) ?

**Comment by atomGit** [comment]
let's say you visit example.com, or any website EXCEPT bitchute.com, and that website has a bitchute video embedded (https://www.bitchute.com/embed/lZhqPaberPs/) - in this case i do not want to preform any redirect

now let's say there's a webpage that has a link to an embedded bitchute video ( `<a href="https://www.bitchute.com/embed/lZhqPaberPs/">video</a>` ) and you click that link - in this case i want to redirect `https://www.bitchute.com/embed/lZhqPaberPs/` to `https://www.bitchute.com/video/lZhqPaberPs/`

**Comment by atomGit** [comment]
did a quick test and this seems to work

for others who may want to do the same, this is how i set up HE:

```
match: url prefix
match rule: https://www.bitchute.com/embed/
custom function:
if (detail.type != "sub_frame") {
	return val.replace('embed', 'video');
}
```
