### ISSUE TITLE
why 4.0.7 version switch my header names to all lower case

### ISSUE THREAD

**Issue by gaiederer** [FirefoxBar/HeaderEditor#128]
If I enter my header name in camel case, header editor converts to all lower case. How do I keep my camel case? According to RFC 2616: 4.2, names are case sensitive. The site I am testing does not recognize all lower case!

Previous versions seemed to work ok, but firefox doesn't like them?

**Comment by sylingd** [comment]
[RFC 2616](https://tools.ietf.org/html/rfc2616.html#section-4.2) says:
Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by gaiederer** [comment]
Yes, field names are case sensitive. Then why does version 4.0.7 of Header Editor convert my mixed case headers to all lower case? It should use them as I type them, not convert them to all lower case.

**Comment by gaiederer** [comment]
Ok, I failed to read correctly. I see case INsensitive. Sorry, I missed that.
