### ISSUE TITLE
chrome 增加 按时间排序 和 删除全部规则 

### ISSUE THREAD

**Issue by sgrjyb** [FirefoxBar/HeaderEditor#13]

**Comment by ivysrono** [comment]
按时间顺序市什么意思？
删除全部+1

**Comment by sgrjyb** [comment]
@ivysrono 按时间排序

**Comment by sylingd** [comment]
批量删除开发中
按时间排序我觉得没有必要

**Comment by sgrjyb** [comment]
@sylingd  导入规则的时候不知道新规则在哪！有规则订阅吗？

**Comment by sylingd** [comment]
没有，也不打算做

**Comment by sgrjyb** [comment]
@sylingd  对于我这种不懂写规则的人可怎么办？按时间排序了?

**Comment by sylingd** [comment]
自己不会写可以找别人写好的啊

**Comment by sgrjyb** [comment]
@sylingd 会不会增加云同步 像xstyle？

**Comment by sylingd** [comment]
可能会，但是也可以直接使用浏览器自带的同步。xstyle不使用是因为，Firefox限制的100kb肯定装不下样式
