### ISSUE TITLE
重定向有点问题

### ISSUE THREAD

**Issue by storyInAugest** [FirefoxBar/HeaderEditor#130]
我在设置百度网盘重定向时
`
匹配规则：
正则表达式
^https?:\/\/pan\.baidu\.com(.*)$
排除
^https?:\/\/pan\.baidu\.com\/(disk|netdisk|.*)\/home.*
重定向至：
常规
https://pan.baiduwp.com$1
`
然后我打开我的网盘 https://pan.baidu.com/netdisk/home 时发现页面加载不完整，本应该规则排除重定向的网站，但后台大部分数据请求却是发向 https://pan.baiduwp.com ，应该是bug吧

另外，顺便建议下，既然设置页面有分组功能，那前台面板设置也可以加入分组规则开启

**Comment by sylingd** [comment]
请给出“后台大部分数据请求”的具体链接

**Comment by storyInAugest** [comment]
我已经知道了，我以为这个重定向是判断页面地址不需要重定向后，然后就按原页面加载，但实际上是加载页面过程中每一次请求都要执行重定向

**Comment by sylingd** [comment]
你可以使用批量选择功能，批量开关一组规则。点击批量选择上方的“选择”可以选择一组规则。

**Comment by storyInAugest** [comment]
现在工具栏点击扩展按钮不是可以直接设置整体的开启关闭，我的意思是在面板上加上分组的开关，其实也不是什么刚需，不加也没问题，感觉用到的场景也不多

**Comment by sylingd** [comment]
我的意思是，批量管理可以直接选择一整个组的规则，达到直接禁用/启用一组规则的效果

**Comment by sylingd** [comment]
直接加分组开关应该不会，你可以使用上面的操作

**Comment by storyInAugest** [comment]
也是，想了下需要临时关闭的时候整体关闭也一样，不过这重定向是不是需要调整下逻辑

**Comment by sylingd** [comment]
怎么调整？

**Comment by storyInAugest** [comment]
能不能做到每次打开新标签页时，判断这个是否需要重定向，如果不需要就按照原页面加载，不执行规则

**Comment by sylingd** [comment]
规则是对应单条请求的，逻辑没有问题，只是你的需求比较特殊。你可以考虑一下自定义函数

**Comment by storyInAugest** [comment]
因为像我这个是重定向到另一个网站，所以原页面的一些脚本图片就加载不了
这个自定义函数怎么写，没看到有教程

**Comment by sylingd** [comment]
你可以尝试使用`originUrl`，具体说明参见[wiki](https://github.com/FirefoxBar/HeaderEditor/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%87%BD%E6%95%B0)和[MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest)
