### ISSUE TITLE
网易考拉登录问题[BUG]

### ISSUE THREAD

**Issue by quboboo** [FirefoxBar/HeaderEditor#131]
**BUG**
下载此扩展是为了解决网易图片不显示的问题，今天发现开启扩展时，网易考拉登录后，始终显示未登录状态

**规则和测试地址**
https://raw.githubusercontent.com/dupontjoy/customization/master/Rules/HeaderEditor/headereditor-all.json

**附加信息**
火狐版本：66.0.5
尝试关闭此扩展后，考拉登录正常；最后定位是规则中的“网易图片不显示”这一条引起考拉登录异常的；开启扩展关闭此规则，考拉登录就正常了

**Comment by sylingd** [comment]
这是规则问题，请前往对应规则维护者处反馈
