### ISSUE TITLE
[BUG]扩展在隐私窗口里显示不正常。

### ISSUE THREAD

**Issue by comoder** [FirefoxBar/HeaderEditor#134]
**BUG**
隐私窗口里显示不正常。点扩展图标显示不完全，而且我在图片上鼠标右键-添加反盗链后打开的页面里也是空白一片啥都显示不出来。火狐版本是68.0b5

**规则和测试地址**
请提供规则内容和测试地址。

**附加信息**
![000000.png](https://i.loli.net/2019/05/31/5cf0e03e0a42652136.png)
![000001.png](https://i.loli.net/2019/05/31/5cf0e03e204b490155.png)

**Comment by sylingd** [comment]
隐身模式不能管理规则，但不影响已有规则的运行。需要管理请在正常模式下进行
