### ISSUE TITLE
[Question] 关于自定义函数中的 detail 参数，和一些建议

### ISSUE THREAD

**Issue by ghcsd** [FirefoxBar/HeaderEditor#135]
环境 ：Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

1、`detail.isFrame` 在[本扩展wiki](https://github.com/FirefoxBar/HeaderEditor/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%87%BD%E6%95%B0#230%E6%96%B0%E5%A2%9Edetail)中描述为`是否为iframe的请求`
https://github.com/FirefoxBar/HeaderEditor/blob/f7fcf2f2eb4ab1c4e26e89a911699d1029be3618/src/background.js#L100
但实际上在(sub-)iframe，的请求都为false。
在中文语言环境下单独提到iframe，习惯上认为是sub-iframe。
所以这样会容易让人产生误会。
建议改为 `detail.isMainFrame`
MDN 中的描述：
>frameId
>> integer. Zero if the request happens in the main frame; a positive value is the ID of a subframe in which the request happens. If the document of a (sub-)frame is loaded (type is main_frame or sub_frame), frameId indicates the ID of this frame, not the ID of the outer frame. Frame IDs are unique within a tab.

2、希望增加 `detail.documentUrl` 属性，
这对排除在某些页面加载的frame资源请求生效很有帮助，只是Chrome不支持。
MDN 中的描述：
>documentUrl
>>string. URL of the document in which the resource will be loaded. For example, if the web page at "https://example.com" contains an image or an iframe, then the documentUrl for the image or iframe will be "https://example.com". For a top-level document, documentUrl is undefined.

3、建议
https://github.com/FirefoxBar/HeaderEditor/blob/f7fcf2f2eb4ab1c4e26e89a911699d1029be3618/src/background.js#L174-L183
https://github.com/FirefoxBar/HeaderEditor/blob/f7fcf2f2eb4ab1c4e26e89a911699d1029be3618/src/background.js#L97-L103
这些属性名称能一一对应官方api的属性（可能跟第一条建议重复，或者直接`const detail = Object.assign({}, details)`跟第二条重复），这样利于减少理解偏差。

4、这一贴 https://www.firefox.net.cn/read-121172#read_368769 4楼中提到
规则类型`阻止请求`不支持自定义函数
https://github.com/FirefoxBar/HeaderEditor/blob/f7fcf2f2eb4ab1c4e26e89a911699d1029be3618/src/background.js#L106-L108
但UI中又允许自定义函数输入，容易让人产生误会。
建议以自定义函数返回值 true/false 来判断是否阻止请求。
或取消UI输入。

**Comment by sylingd** [comment]
1.实际上我已经发现这个属性描述不准确并且不实用。下个版本已经改为直接传入frameId
2.会添加
3.我在考虑这样做有没有别的问题，如果没有问题的话下个版本会改成这样。但是也会兼容之前版本的写法
4.属于BUG，已经修复
