### ISSUE TITLE
[Question] unsafe-eval in csp inside manifest.json

### ISSUE THREAD

**Issue by Maryse47** [FirefoxBar/HeaderEditor#137]
Hello, could you tell me why do you set [unsafe-eval in csp policy inside manifest.json](https://github.com/FirefoxBar/HeaderEditor/blob/53b084a0146aff87f5e063806263200451e4e412/src/manifest.json#L21)?

[This is dangerous permission](https://old.reddit.com/r/firefox/comments/cgfl6e/list_of_addons_that_use_unsafeeval_or/) that shouldn't be normally allowed on AMO. Moreover [according to this comment](https://old.reddit.com/r/firefox/comments/cgfl6e/list_of_addons_that_use_unsafeeval_or/eujeyvo/), this permission isn't even used in this addon. Can you explain this?

**Comment by sylingd** [comment]
Custom function required unsafe-eval

**Comment by Maryse47** [comment]
Ok, can you tell me if mozilla reviewers ever asked about this permission or if this addon updates are under manual reviews process?

**Comment by sylingd** [comment]
In my memory they asked me twice, the  latest one is about 2 months ago

**Comment by sylingd** [comment]
I have read the post on Reddit, the code which use `unsafe-eval` is at [src/options/App.vue#L657](https://github.com/FirefoxBar/HeaderEditor/blob/master/src/options/App.vue#L657) and [src/core/rules.js#L23](https://github.com/FirefoxBar/HeaderEditor/blob/master/src/core/rules.js#L23)

**Comment by Maryse47** [comment]
Thank you for providing those answers and documenting this.
