### ISSUE TITLE
[BUG]自定义函数疑似无法实现天涯反盗链

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/HeaderEditor#145]
**BUG**
如题

**规则和测试地址**
请提供规则内容和测试地址。
https://bbs.kafan.cn/thread-2102542-1-1.html

常规模式没问题：
```
      "enable": true,
      "name": "Anti-Anti-Leech-TianYa",
      "ruleType": "modifySendHeader",
      "matchType": "regexp",
      "pattern": "^https?://img[1-3].laibafile.cn/",
      "exclude": "",
      "isFunction": false,
      "action": {
        "name": "referer",
        "value": "https://bbs.tianya.cn/"
      },
      "group": "Free"
    }
```

函数模式就天涯不生效：
https://github.com/ivysrono/HeaderEditorRules/blob/master/src.js

**附加信息**
Win 10
Firefox 71.0.1 x64
HE 4.0.7

**Comment by sylingd** [comment]
因HTTPS页面引用HTTP资源，本身不会有Referer头。你的代码只判断了存在Referer的情况下进行修改，没有处理本身不存在Referer的情况

**Comment by ivysrono** [comment]
```
const editReferer = ref => {
  val.push({ referer: ref });
};
```
该成这样反而完全无效了

**Comment by ghcsd** [comment]
这显然错了,应该是
```js
val.push({ name: 'Referer',  value: ref });
```

题外：@sylingd 能否给管理规则页面标签加个图标（favicon），打开多个标签能有更好辨别度。

**Comment by ivysrono** [comment]
原来如此，多谢 @ghcsd

**Comment by sylingd** [comment]
> ```
> const editReferer = ref => {
>   val.push({ referer: ref });
> };
> ```
> 
> 改成这样反而所有站点都完全无效了。
> 插了下，HTTPS页面引用HTTP资源时浏览器就不会发送Referer头，不知道常规模式是怎么实现的？

常规模式有判断，如果已经存在就替换，不存在就添加
