### ISSUE TITLE
[BUG] dev 分支中一些 bug 和建议

### ISSUE THREAD

**Issue by ghcsd** [FirefoxBar/HeaderEditor#146]
1. https://github.com/FirefoxBar/HeaderEditor/blob/5057c8cfadc3a183f702ffe394adc0c733da78ee/src/options/App.vue#L1066
应该为 `url: utils.t('url_help')`
---
2. https://github.com/FirefoxBar/HeaderEditor/blob/5057c8cfadc3a183f702ffe394adc0c733da78ee/src/options/App.vue#L552
和
https://github.com/FirefoxBar/HeaderEditor/blob/5057c8cfadc3a183f702ffe394adc0c733da78ee/src/options/App.vue#L560
`options.collapseGroup` 应该都为 `options['manage-collapse-group']`
---
3. https://github.com/FirefoxBar/HeaderEditor/blob/5057c8cfadc3a183f702ffe394adc0c733da78ee/src/options/App.vue#L465
`this.options.enableHeaderPrompt` 应该为 `this.options['show-common-header']`
---
4. https://github.com/FirefoxBar/HeaderEditor/blob/5057c8cfadc3a183f702ffe394adc0c733da78ee/src/options/App.vue#L245
`v-show` 应改为 `v-if`，否则自动完成下拉列表的宽度不正确，
原因是元素在 `display: none` 下无法获取(计算)其子孙元素的宽度。
改为 `v-if` 后让其即时渲染就能避免这个问题。这应该是 vue-material 的 bug。
---
5. 希望管理规则页面标签加个图标（favicon），打开多个标签能有更好辨别度。
https://github.com/FirefoxBar/HeaderEditor/blob/5057c8cfadc3a183f702ffe394adc0c733da78ee/src/options/options.html#L7
```html
    <link rel="icon" href="../assets/images/128.png">
```
---

PS：希望早日合并正式发布，非常期待修改 response 数据的功能。

**Comment by sylingd** [comment]
已修复

**Comment by sylingd** [comment]
因Mozilla屡次因为我所绑定的邮箱屏蔽我的账号，4.1.0将不会发布Firefox版本

**Comment by ghcsd** [comment]
> 
> 
> 因Mozilla屡次因为我所绑定的邮箱屏蔽我的账号，4.1.0将不会发布Firefox版本

好吧，希望以后能解决。
