### ISSUE TITLE
重定向规则达不到预期目的

### ISSUE THREAD

**Issue by xinggsf** [FirefoxBar/HeaderEditor#15]
匹配规则：`^(http://www\.ftchinese\.com/story/\d+)`
排除规则：`.+full=y`
重定向至：`$1?full=y`
网址：http://www.ftchinese.com/story/001074155?dailypop
重定向后：http://www.ftchinese.com/story/001074155?full=y?dailypop
没有达到去掉网址参数的目的。原来应该重定向http://www.ftchinese.com/story/001074155?full=y

再问问作者，重定向规则的自定向函数有什么参数，是JS中replace函数的回调吗？

**Comment by sylingd** [comment]
是。实际执行的JS函数：url.replace(new RegExp('正则表达式'), '目标地址')

**Comment by sylingd** [comment]
正常规则应该是：^http://www\.ftchinese\.com/story/(\d+)(.*?)$
重定向至：
http://www.ftchinese.com/story/$1?full=y

**Comment by dupontjoy** [comment]
重定向去跳转规则都没有生效
匹配规则：https?:\/\/outgoing\.(prod\.mozaws|mozilla)\.(net|org)\/.*(http.*)
排除规则：
重定向至：$3
网址：https://outgoing.mozilla.org/v1/5c2a5620285210f7267fdf87cfd39943f03f42538d2d98eec0b0cf5565dbca23/http%3A//vimium.github.io/
Redirector扩展可以跳转, headerEditor不行

**Comment by sylingd** [comment]
@dupontjoy 正则写错了吧？
![qq 20170914211531](https://user-images.githubusercontent.com/5326684/30431702-03bfba36-9992-11e7-99de-e964e60272d4.png)

**Comment by dupontjoy** [comment]
正则没用代码格式, 斜杠被自动去掉了, 已改

**Comment by xinggsf** [comment]
@sylingd 
嗯，规则改为`^(http://www\.ftchinese\.com/story/\d+).*$`就好了！
@dupontjoy 
试试规则改为`^https?://outgoing\.(prod.mozaws|mozilla)\.(net|org)/.*?(http.+)$`
网址匹配以http开头，最好加上^，这样效率高

**Comment by dupontjoy** [comment]
@xinggsf 还是没有效果

**Comment by xinggsf** [comment]
@dupontjoy 在正则工具中测试通过啊！
这扩展正则复杂些就失效

**Comment by sylingd** [comment]
原因是URL经过了编码，浏览器认为这个URL非法
和正则复杂与否没有关系

**Comment by sylingd** [comment]
已经增加自动解码功能，可有效简化此类问题

**Comment by dupontjoy** [comment]
什么时候发布新版安装包

**Comment by sylingd** [comment]
@dupontjoy 后续工作（界面调整、BUG修复、本地化）完成后，预计今天或者明天

**Comment by dupontjoy** [comment]
还有个问题, 
新版增加了"分组"功能, 但是在导出规则时, 分组的信息没有保存的样子

**Comment by sylingd** [comment]
@dupontjoy 就是这样设计的

**Comment by ivysrono** [comment]
@dupontjoy #16
