### ISSUE TITLE
[BUG]火狐界面显示空白

### ISSUE THREAD

**Issue by Kumiri** [FirefoxBar/HeaderEditor#154]
火狐版本：72.0.1
插件版本：4.1.1
**BUG**
莫名其妙界面一片空白！！如下图所示，卸载插件重新安装还是如此。
※重装插件前，只要能“启用Header Editor”也能正常使用。重装插件后，连“后台管理页”都进不去。
<img src="https://i.vgy.me/NehNhQ.png">

Chrome后台地址：chrome-extension://eningockdidmgiojffjmkdblpjocbhgh/options/options.html
火狐后台地址呢？？

**Comment by sylingd** [comment]
全新安装了Firefox 72.0.1，表示正常
![image](https://user-images.githubusercontent.com/5326684/72356071-9a47c800-3723-11ea-9f68-aa5a636d007f.png)

请尝试：
* 打开`about:debugging`
* 找到“此Firefox” - “扩展” - “Header Editor” - “Manifest URL”，如`moz-extension://f7b71021-6c43-4af7-9112-13e209a80ad3/manifest.json`
* 将其前半段复制，然后加上`/options/options.html`打开，例如`moz-extension://f7b71021-6c43-4af7-9112-13e209a80ad3/options/options.html`
* 是否可以正常显示？如果不可以，按F12，找到控制台，查看是否有报错信息。

**Comment by Kumiri** [comment]
@sylingd 找到问题，我猜错了BUG起因。是72.0之后“折叠菜单”里显示突然异常，因为从68.0起都在“折叠菜单”里使用“Header Editor”。

还有谢谢你教我，现在知道插件后台地址获取方式。
<img src="https://i.vgy.me/wp1y7U.gif">

将“Header Editor”移出 折叠菜单 就能正常使用。
希望未来还能在“折叠菜单”里正常使用“Header Editor”。

**Comment by sylingd** [comment]
已在feat/react中修复
