### ISSUE TITLE
分组等的进一步改进建议

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/HeaderEditor#16]
2.3.0
Related: #14 

- [ ] 导出信息不包含分组设置。导入当然也就没有了。

- [x] 不能批量移动规则到指定分组。

- [x] 目前删除分组是将组内规则改回到未分组中，其实是单纯删除组标签。但很需要 只删除组内全部规则/删除组标签及组内规则 的选项。毕竟现在全选是跨组别的。

**Comment by ivysrono** [comment]
#14

**Comment by sylingd** [comment]
1.机制不同，也是考虑到其他一些原因，所以，不打算让分组可以导入/导出
2.批量移动正在考虑中
3.批量删除待优化

**Comment by dupontjoy** [comment]
我比较需要你的第1点建议

**Comment by sylingd** [comment]
现在可以跨组实现导入和导出，所以分组也不能实现
