### ISSUE TITLE
[BUG]file-url Firefox 无法正常重定向

### ISSUE THREAD

**Issue by polyproline** [FirefoxBar/HeaderEditor#166]
**BUG**
我对于googleapi.com 的内容重定向
发现firefox 直接访问 可以重定向到 geekzu.org
但是 如果网页内资源 不可以 重定向

**规则和测试地址**
重定向请求
^https?:\/\/fonts\.googleapis\.com\/(.*)$
https://fonts.geekzu.org/$1

测试网站
file:///{$HOME}/.rustup/toolchains/nightly-x86_64-pc-windows-gnu/share/doc/rust/html/rustc/index.html

**附加信息**
Chromium 可以使用

**Comment by sylingd** [comment]
这是Firefox本身的限制
