### ISSUE TITLE
不支持新增请求头字段么?

### ISSUE THREAD

**Issue by dupontjoy** [FirefoxBar/HeaderEditor#17]
页面已经有的请求头名称如Referer和User-Agent, HE可以更改它的内容

如果页面不存的头名称如Save-Data, 我用HE来设置, 没有生效, 是不是因为不支持新增头名称呢?

**Comment by sylingd** [comment]
经测试不存在问题

**Comment by dupontjoy** [comment]
好吧, 可能新版无意间就修复了
今天想起就问了一下, 我应该再测试一下, 打扰了

**Comment by sylingd** [comment]
2.1.2版本修复的
