### ISSUE TITLE
[BUG] 重新導向的替換方式

### ISSUE THREAD

**Issue by bestpika** [FirefoxBar/HeaderEditor#171]
**BUG**

我有一個重新導向的規則在 Regex101 測試過沒問題，但是在 HE 卻無法正常運作

**规则和测试地址**

規則: `^https?:\/\/(?:go|l)\.plurk\.com\/\?url=([^&]+)`
網址: `https://l.plurk.com/?url=http%3A%2F%2Fphate.io&id=33357X911862&xs=1`
重導: `$1`

之前應該是整串網址替換成 `$1` 的內容而不是命中的部分替換

**附加信息**

![image](https://user-images.githubusercontent.com/5698157/87263194-f763e100-c4ee-11ea-9570-b1e3e32ca991.png)
![image](https://user-images.githubusercontent.com/5698157/87263218-0d71a180-c4ef-11ea-83c4-ba58dbcff6b6.png)

**Comment by sylingd** [comment]
请截图完整规则

**Comment by bestpika** [comment]
![Header Editor](https://user-images.githubusercontent.com/5698157/87263485-e36caf00-c4ef-11ea-950d-181c44ae3d01.png)

**Comment by bestpika** [comment]
照理來說他應該要是這樣
![image](https://user-images.githubusercontent.com/5698157/87263523-01d2aa80-c4f0-11ea-8be5-e67c8311a94d.png)
但是 HE 卻沒辦法停在 `&` 前面

**Comment by bestpika** [comment]
忘了說我的 HE 版本是 Chrome 的 v4.1.1

**Comment by sylingd** [comment]
没有问题啊，匹配停在&前面，并且&前面的部分被替换成$1，得到的结果确实是你截图的结果

**Comment by bestpika** [comment]
那是上次改版有改過什麼嗎？
我記得之前是整串網址會被替換成 `$1` 的內容而不是命中的部分

**Comment by sylingd** [comment]
> 那是上次改版有改過什麼嗎？
> 我記得之前是「整串網址」會被替換成 `$1` 的內容而不是命中的部分
> 因為我這規則用很久了，當初寫完測試是正確的
> 只是很久沒遇到這網址一遇到就發現不正常

这一块从有到现在没有任何更改
