### ISSUE TITLE
[Question] 重新導向是否能套用在 <script /> 引用的外部資源？

### ISSUE THREAD

**Issue by bestpika** [FirefoxBar/HeaderEditor#172]
這個網站
<https://www.dailyindiegame.com/>
有一段
`<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>`
我試著寫了一個規則去強制他從 HTTP 重導到 HTTPS
![Header Editor](https://user-images.githubusercontent.com/5698157/87266561-2894df00-c4f8-11ea-951b-61bb1cbd7048.png)
但是我在開發人員工具卻發現他沒有運作
![image](https://user-images.githubusercontent.com/5698157/87266620-42cebd00-c4f8-11ea-915f-3f0ee61bb8d0.png)
請問是這個功能不能套用到這種方式引用的外部資源？
還是我哪裡寫錯？

**Comment by sylingd** [comment]
这是因为浏览器直接屏蔽了HTTPS下的HTTP资源请求。
浏览器屏蔽了对这个资源的请求，也就是说，根本就不存在对这个资源的请求，所以无法重定向。
