### ISSUE TITLE
重定向能否:仅地址栏URL才触发重定向

### ISSUE THREAD

**Issue by dnknn** [FirefoxBar/HeaderEditor#173]
### 重定向能否:仅地址栏URL才触发重定向, 即不是DOM内部的URL.

![Pic-200723_1656](https://user-images.githubusercontent.com/10995302/88268753-84841280-cd05-11ea-8398-1a805737f2e6.png)

> 先解释下场景: 

1. 比如说浏览器地址栏URL是`111.com` 这个页面是100多张图片缩略图.
`aaa.111.com/img?xxx`是其旗下缩略图,加载很快. 去掉?xxx是单张原图.
#### 然后就想手动新标签打开`aaa.111.com/img?xxx`会自动重定向去掉`?xxx`参数来查看原图.

2. 于是就重定向`aaa.111.com/img?xxx`&emsp;👉&emsp;`ccc.111.com/img`
此时在111.com这个页面里面含有的aaa.111.com/img?xxx资源都会全部被重定向,对吧.
### 💥👿那么问题来了, 每次打开页面就会非常非常缓慢, 因为每次都必须下载加载.

所以说,重定向能否有个新功能选项: 仅针对地址栏的URL才触发重定向.
也就是说这个要重定向的aaa.111.com/img?xxx必须是在地址栏**出现或跳转或手动打开**,才会去重定向. 而不是在111.com的内部进行重定向.

- ### 即重定向仅仅是针对地址栏URL(术语类似于location host), 而不针对页面DOM内部.
- ### 或者说类似于Tampermonkey脚本匹配的`// @include`&emsp;`// @match`	元数据,仅当匹配主机域名或iframe域名才会触发匹配.

或者像👇 `location.href` 只认暴露出来的URL(地址栏URL),不认HTML/DOM/等内部隐藏URL
```
(function() {
    'use strict';
    var host = location.href;
    if(/http:abc.com\/img/.*/.test(location.href))
	   {
     location.href=location.href.replace(/img.*/,"")
    }
})();
```

最后发现: Redirector	这个扩展可以做到这点
https://chrome.google.com/webstore/detail/ocgpenflpmgnfapjedencafcfakcekcd
https://github.com/einaregilsson/Redirector
https://einaregilsson.com/redirector/
![Pic-200723_1722](https://user-images.githubusercontent.com/10995302/88271062-3244f080-cd09-11ea-9f7e-dbda35c3cbf0.png)

这样的功能 Header Editor能实现吗❓

**Comment by sylingd** [comment]
可以使用自定义函数

**Comment by dnknn** [comment]
> 可以使用自定义函数，判断detail.type === 'main_frame'即可

可是自定义函数很复杂,一点都不懂哈
