### ISSUE TITLE
[Question] 请问可改 addons.mozilla.org 的网址吗？

### ISSUE THREAD

**Issue by cc85** [FirefoxBar/HeaderEditor#191]
请问可改 addons.mozilla.org 的网址吗？
　　例如：en-US 改 zh-CN （ https://addons.mozilla.org/en-US/firefox/addon/header-editor/ 改 https://addons.mozilla.org/zh-CN/firefox/addon/header-editor/ ）
　　因为我怎么写，网址都不会变，所以上来问，谢谢。

**Comment by sylingd** [comment]
Chrome可以
Firefox受浏览器限制不可以
