### ISSUE TITLE
[Question]该扩展是否被官方发布到了edge扩展商店？

### ISSUE THREAD

**Issue by lychichem** [FirefoxBar/HeaderEditor#203]
无意中因为需要用下反-防盗链，结果在edge商店找到了这个：https://microsoftedge.microsoft.com/addons/detail/header-editor/djbcdihpmcbpkljpjibeiedjenilallo
![image](https://user-images.githubusercontent.com/9316590/154831943-1053c40c-42ee-486f-bd5c-73ee6880bced.png)
看图标和界面完全一致，链接也是链接到官方页面，但是鉴于edge商店的黑历史，还是想来问下团队，这个发布人是什么身份

**Comment by lychichem** [comment]
@yfdyh000 @sylingd

**Comment by sylingd** [comment]
你好，目前没有

**Comment by lychichem** [comment]
> 你好，目前没有

那能否鉴定一下edge商店这个版本的代码呢？主要是怕有人加料影响团队声誉

**Comment by RimeTW** [comment]
> > 你好，目前没有
> 
> 那能否鉴定一下edge商店这个版本的代码呢？主要是怕有人加料影响团队声誉

這直接 report 讓它下架就好了不是？

**Comment by lychichem** [comment]
> > > 你好，目前没有
> > 
> > 
> > 那能否鉴定一下edge商店这个版本的代码呢？主要是怕有人加料影响团队声誉
> 
> 這直接 report 讓它下架就好了不是？

但是有人帮忙上架未加料版的，对我来说是个方便的事，虽然举报我能直接联系edge社区经理举报了

**Comment by zhtw2013** [comment]
> > > > 你好，目前没有
> > > 
> > > 
> > > 那能否鉴定一下edge商店这个版本的代码呢？主要是怕有人加料影响团队声誉
> > 
> > 
> > 這直接 report 讓它下架就好了不是？
> 
> 但是有人帮忙上架未加料版的，对我来说是个方便的事，虽然举报我能直接联系edge社区经理举报了

開發組無法為這位不認識的套件上傳者背書
假如這版沒問題，那下一版呢？

如果他上傳的下一版加料，是不是有人會找來這篇
說「開發者幫他背書了，所以是開發者的責任。」

**Comment by zhtw2013** [comment]
剛剛已將 4.1.1 版上傳至 Edge 應用商店
等待 7 天審核

**Comment by lychichem** [comment]
> 剛剛已將 4.1.1 版上傳至 Edge 應用商店
> 等待 7 天審核

那我还是去把现在这个举报下去吧，毕竟第三方的东西有点不放心

**Comment by zhtw2013** [comment]
https://microsoftedge.microsoft.com/addons/detail/header-editor/afopnekiinpekooejpchnkgfffaeceko

已上架
