### ISSUE TITLE
贴吧 豆瓣 去掉不了跳转

### ISSUE THREAD

**Issue by sgrjyb** [FirefoxBar/HeaderEditor#22]
name: "贴吧链接去跳转",
    http://jump.bdimg.com/safecheck/
    to: "http://tieba.baidu.com/",

 "douban去跳转",
 "^https?:\\/\\/www\\.douban\\.com\\/link.*\\/\\?url=(.*)$",
  "to": "$1",

**Comment by sylingd** [comment]
基本上不可能存在部分网站能跳转，部分不能的情况。
如果出现，先验证自己匹配规则、调整地址无误，再报issue。
报issue提供完整的编辑界面截图、匹配规则、跳转规则、测试地址，否则作者无法测试，也无法判断哪里的问题

**Comment by sgrjyb** [comment]
https://www.douban.com/group/topic/107728489/

http://tieba.baidu.com/p/5335304206

我就是想让你看看规则有没有问题

**Comment by sylingd** [comment]
豆瓣的地址是`https://www.douban.com/link2/?url=跳转目标`，你自己正则没写对

**Comment by sylingd** [comment]
报issue提供完整的编辑界面截图、匹配规则、跳转规则、测试地址

**Comment by sylingd** [comment]
作者的精力没那么多，不可能每次遇到不正常的情况都叫作者帮你看。遇到不正常的情况先自己用JS代码调试规则，确认自己规则没问题再报告issue

**Comment by sgrjyb** [comment]
![douban](https://user-images.githubusercontent.com/28247198/30783203-70963c16-a171-11e7-8c2e-aac5f9c3e774.PNG)
豆瓣测试地址：https://www.douban.com/group/topic/107728489/
![default](https://user-images.githubusercontent.com/28247198/30783209-937a641e-a171-11e7-830c-ca034743c318.PNG)
知乎 1.按时间排序无法跳转 测试地址：https://www.zhihu.com/question/19594682/answers/created
2知乎专栏无法跳转 https://zhuanlan.zhihu.com/p/29561196
![tieba](https://user-images.githubusercontent.com/28247198/30783174-15b33f6a-a171-11e7-9f54-8093028f2af8.PNG)
贴吧测试地址：http://tieba.baidu.com/p/5335304206

**Comment by dupontjoy** [comment]
我也觉得重定向功能有点问题, 知乎这个规则, 在线检测没问题, 但放在HE中就没生效, 有点奇怪

![5](https://user-images.githubusercontent.com/4965288/30791594-27e342be-a1e6-11e7-820e-3406986482af.jpg)

**Comment by sylingd** [comment]
@sgrjyb 豆瓣规则少了*号，知乎规则多了反斜杠（\）
@dupontjoy 经测试有效，不存在此问题
![qq 20170925135953](https://user-images.githubusercontent.com/5326684/30794276-d1abf044-a1f9-11e7-83b0-b82d05da0217.png)
![qq 20170925135908](https://user-images.githubusercontent.com/5326684/30794260-bd5e44f2-a1f9-11e7-909c-dedb2047c3f2.png)

**Comment by sgrjyb** [comment]
@sylingd 1.经测试修改知乎规则后还是无效 请打开我上面的链接，2.豆瓣在哪加* , 3.贴吧怎么重定向？

**Comment by sylingd** [comment]
经测试，扩展本身不存在问题，规则问题请自行修改，作者不是客服，相关文档：[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Regular_Expressions)

**Comment by sgrjyb** [comment]
我用的是dupontjoy 的规则 ，你确定能去我上面知乎的链接 ？规则只能去按默认排序的链接！

**Comment by sylingd** [comment]
规则覆盖不完全的问题，找维护者，作者不负责维护规则

**Comment by sgrjyb** [comment]
@dupontjoy 在线检测的网站是？

**Comment by dupontjoy** [comment]
@sgrjyb http://regex.zjmainstay.cn/

**Comment by dupontjoy** [comment]
多试验几次, 规则应该是生效了
只不过还是会看到短暂的跳转动件, Zhihu和douban可能看不出效果
测试: https://addons.mozilla.org/zh-CN/firefox/addon/ublock-origin/?src=search
AMO去跳转就很明显, 载入时也会看到outgoing短暂出现一下, 然后才打开目标网址
如果不用去跳转规则的话, 就会停在outgoing跳转页, 需要手动点击才能打开目标网址
所以说HE的去跳转功能应该没问题了, 但是机制与Redirector可能有点不一样

**Comment by sylingd** [comment]
不能确定规则是否有问题的，更新2.3.2，使用编辑界面自带的测试功能测试规则
AMO版本审核中

**Comment by sgrjyb** [comment]
@sylingd 规则生效了，但页面链接还是显示 https://www.douban.com/link2/?url=https%3A%2F%2Fzhuanlan.zhihu.com%2Fp%2F29561196 ，点击链接没有跳转是bug吗？

![douban](https://user-images.githubusercontent.com/28247198/30801908-6e9e64a0-a217-11e7-9897-a3718e092f57.PNG)

**Comment by sylingd** [comment]
F12查看是否有网络请求，如果状态不是200/301/302则代表已经在浏览器内部重定向了

**Comment by dupontjoy** [comment]
@sgrjyb 会很快就跳到目标页面, douban和zhihu跳转本来就快, 可能感觉不出差距

**Comment by sgrjyb** [comment]
@sylingd 

![307](https://user-images.githubusercontent.com/28247198/30809068-0dc7d082-a233-11e7-801c-857cf6b1612b.PNG)

**Comment by sylingd** [comment]
我都说了不是200/301/302就没问题

**Comment by sgrjyb** [comment]
@sylingd 我添加规则的时候点了全部 现在进不了设置怎么办？

**Comment by sylingd** [comment]
1.打开Chrome-扩展程序
2.勾上开发者模式
3.点击Header Editor下，“检查视图”后的“背景页”
4.输入`getRules('request')`回车
5.逐项展开，找到你误添加的规则，记下id（如图所示）
![default](https://user-images.githubusercontent.com/5326684/30813919-504c2256-a241-11e7-99e4-e8e8f9cec55d.PNG)
6.输入`deleteRule('request', 刚才你记下来的id)`回车，例如`deleteRule('request', 24)`
7.输入`updateCache('request')`回车

**Comment by sgrjyb** [comment]
@sylingd 太感谢了
