### ISSUE TITLE
[Question]why did Header Editor for edge on macos not work

### ISSUE THREAD

**Issue by robot527** [FirefoxBar/HeaderEditor#228]
为什么Header Editor在 macos 系统的 edge 浏览器上不能正常工作，同样的 规则在
1. macos 系统的Firefox 浏览器上工作正常；
2. win10 系统的edge 浏览器上工作正常。

但是 macos 系统的 edge 浏览器上就没能生效。

规则内容：

```
匹配类型: 正则表达式
匹配规则: ^http(s?)://(www\.)?bing\.com/?(.*)
执行类型: 常规
头名称: x-forwarded-for
头内容: 8.8.8.8
```

**Comment by sylingd** [comment]
实际上，我前两天才在mac的edge dev上用了类似的规则，是正常的……

**Comment by robot527** [comment]
> 

这边版本：
Microsoft Edge
版本 110.0.1587.69 (正式版本) (x86_64)

**Comment by robot527** [comment]
> 实际上，我前两天才在mac的edge dev上用了类似的规则，是正常的……

这边版本：
Microsoft Edge
版本 110.0.1587.69 (正式版本) (x86_64)

**Comment by namniav** [comment]
Just in case you missed this: Is Header Editor allowed to access(read or modify) data on current website? Check the browser setting in `edge://extensions/`.
BTW, the `x-forwarded-for` hack is already fixed by bing.

**Comment by robot527** [comment]
> 

是的，被 ban 了。
