### ISSUE TITLE
火狐版导入chrome的规则失败

### ISSUE THREAD

**Issue by xinggsf** [FirefoxBar/HeaderEditor#23]
火狐53x64版
控制台全部不停的输出同样的错误，想复制都不行

**Comment by sylingd** [comment]
经测试无复现问题。
请确认Header Editor版本为最新版本（目前为2.3.0）
若仍有问题，请截图控制台

**Comment by xinggsf** [comment]
`
error { target: IDBOpenDBRequest, isTrusted: true, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 1506305181397000, cancelBubble: false, originalTarget: IDBOpenDBRequest, explicitOriginalTarget: IDBOpenDBRequest }  storage.js:8:4
error { target: IDBOpenDBRequest, isTrusted: true, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 1506305181399000, cancelBubble: false, originalTarget: IDBOpenDBRequest, explicitOriginalTarget: IDBOpenDBRequest }  storage.js:8:4
`
终于复制到了，全是这样的报错信息

**Comment by sylingd** [comment]
1.尝试关闭隐私模式
2.尝试重新安装该扩展

**Comment by xinggsf** [comment]
没一点用！
另外也不能添加规则，不知道是不是我一个人这样的情况

**Comment by sylingd** [comment]
这是因为Header Editor无法打开数据库
因出现情况及其偶然，无法复现，原因未知，推测是Firefox的BUG。因此也无法修复

**Comment by xinggsf** [comment]
但我在控制台执行：
indexedDB.open("headereditor", 2);
没报错

**Comment by sylingd** [comment]
因为打开indexeddb的过程是异步的，所以，如果出错，会通过onerror回调触发，例如：
```
let dbOpenRequest = window.indexedDB.open("headereditor", 2);
dbOpenRequest.onerror = function(event) {
console.log(event);
};
```

**Comment by xinggsf** [comment]
嗯嗯，是我粗心了，试了一下这段代码。
报错

**Comment by sylingd** [comment]
我也用过pcx53，不过，我没有遇到这个问题。
之前有人报告过类似问题，我也测试过，通过VSCode的debugger自动新建一个新的Profile，就会出现这种问题。具体原因不清楚。可能是Firefox的BUG
