### ISSUE TITLE
"homepage_url" 为何不指向 Github

### ISSUE THREAD

**Issue by yfdyh000** [FirefoxBar/HeaderEditor#24]
http://team.firefoxcn.net/ 仅中文，且不便于错误报告。
有 https://github.com/FirefoxBar 就足够了。

**Comment by sylingd** [comment]
homepage是首页的意思。项目组首页就是这个网址。
帮助链接在管理界面是有的，且支持多国语言

**Comment by yfdyh000** [comment]
但这个首页应该是附加组件的首页，不填默认是AMO上的附加组件页面。
外国人看不懂中文，会一脸懵逼吧。

**Comment by sylingd** [comment]
如果他们需要帮助，管理界面的帮助按钮是最直观、最方便、也是最好找到的

**Comment by yfdyh000** [comment]
感觉不直观，刚刚去仔细找才看到。wiki也是，English偏下，我改了一下。
该网址能够在扩展禁用/打不开的情况下使用。

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/homepage_url: `URL for the extension's home page.`，应该写扩展的首页。虽然也不是很严格，也有作者写个人网站、博客等。
不明白写项目组网址有多大用。如果要宣传，可以在管理页面边角放链接/图块，更有曝光率，帮助按钮也是应该在边缘。
此外，虽然此扩展看上去很强大，但没有组织订阅或分享项目，很难上手。

**Comment by sylingd** [comment]
不知道你有没有用最新版？
直接下载并导入的功能除了无法自动更新，和订阅已经基本上没有区别
分享规则的功能是有的

**Comment by yfdyh000** [comment]
不知道从哪里导入、哪里分享。选项、项目主页、wiki、AMO页面，都没有看到。

**Comment by sylingd** [comment]
![image](https://user-images.githubusercontent.com/5326684/30779336-51e64af0-a120-11e7-9c68-7e462b22c57c.png)
那么多按钮，到底是还不够大还是怎么样

**Comment by yfdyh000** [comment]
导入导出需要文件。下载规则默认空记录，没有提供可用规则的列表（比如开个wiki页）或搜索方法。
按钮要有区别，比如帮助按钮的颜色、位置和大小最好有区分，否则就只能每次逐个看文字定位置。

**Comment by sylingd** [comment]
导入导出，不需要文件，需要什么？
提供常见规则可以考虑
帮助按钮我尝试了一下，没有找到很好的位置

**Comment by yfdyh000** [comment]
导入所需要的json文件……新用户是没有、不了解的。
见上。应该提供一个保持更新的名单链接。Github wiki可以，但国内用户访问有困难。
至少间距加大一点，形成功能分块。完全居右可能被忽略。

**Comment by sylingd** [comment]
导入和导出功能本来就是一对
