### ISSUE TITLE
Remove request/response headers

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#25]
Thanks for the WebExtension! Look forward to using it more

Currently, it looks like it is only possible to modify request/response headers but can you add an option to remove request/response headers?

**Comment by sylingd** [comment]
In most cases, set one header to empty have same effetc with remove it.
If you really want to remove one header, you can use custom codes.

**Comment by grenzor** [comment]
I've tried removing headers by setting their value as empty but from what I've tested they're never removed.

Is it possible you can give me an example of a custom code that works in removing the header?

**Comment by sylingd** [comment]
Of couse. For example, the following code will remove "User-Agent":
```javascript
for (let a in val) {
	if (val[a].name === 'User-Agent') {
		delete val[a];
		break;
	}
}
```

**Comment by grenzor** [comment]
Thanks. Also, just tested it seems setting the value of the header as empty does work on latest stable version of FF. But it wasn't working on Nightly FF 58 which is where I tested it.

**Comment by sylingd** [comment]
@grenzor I will test it later

**Comment by sylingd** [comment]
I have tested on Firefox 58.0a1, it works well.
Please tell me more information, such as, which features do not work, and how to reproduce it

**Comment by grenzor** [comment]
Interesting, just tested and it does indeed work. Don't know why it didn't before.

One thing that might not be working is modify response headers but I'm not sure if it is me doing something wrong. I tried modifying and also adding a new response header but none of the modifications are showing in network requests. Could you check if it works properly for you?

Also 1 last thing I noticed is that headers of "behind-the-scene" requests such as OCSP requests or Safebrowsing updates aren't modified. Is this due to some kind of WebExtension limitation?

**Comment by sylingd** [comment]
Modify headers won't be shown in Developer Tools. You can view the modified headers by write a server script (for example, a php script)
WebExtension have low authority, so maybe the requests by browser (such as OSCP) can not be modified by WebExtensions.
