### ISSUE TITLE
Add header option so it works with site changes

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#26]
Currently it looks as though if you add an header the header you add is the only value that is set and the server/webpage set headers won't be added. That is the usual use-case scenario, but is it possible to create something like a tickbox option that allows someone to add/modify header but also allows the website you're on to add on to the header that the user specified?

Example:
I add cookie=myaddedcookie=abc
then site can also add on to my header too like
cookie=myaddedcookie=abc;siteaddedcookie=abc;

**Comment by sylingd** [comment]
This is not very common. You can implement it with custom code.

**Comment by grenzor** [comment]
Thanks, that works for me!

On a somewhat related question, do you know of a custom code that is able to remove a specific header value, example: remove value 'ball' from Cookie: ball=1&cat=1 so it then becomes Cookie: cat=1

I messed around with some JS code to do this but wasn't able to get one working since my knowledge of JS is weak

**Comment by sylingd** [comment]
You can use `replace` function. Example:
```javascript
for (let a in val) {
	if (val[a].name === 'Cookie') {
		val[a].value = val[a].value.replace('ball=value', '');
		break;
	}
}
```

If you want to learn more about Javascript, you can visit [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by grenzor** [comment]
Thanks again and also for the link, will look into it.

If I see correctly, the code would work only if the value in ball=value is constant, but what if the value is randomly generated?

**Comment by sylingd** [comment]
You can use regular expression. Documention: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions). For example:
```javascript
val[a].value = val[a].value.replace(/ball=(.*?)/, ''); // will remove ball=*
val[a].value = val[a].value.replace(/ball=(\d+)/, ''); // will remove ball=[number], such as ball=12345
```

**Comment by grenzor** [comment]
Interesting, I'll look more into regular expressions. Thank you!
