### ISSUE TITLE
9/29nightly开启扩展后导致浏览器假死

### ISSUE THREAD

**Issue by kkren** [FirefoxBar/HeaderEditor#28]
启用扩展后重新启动浏览器，5秒后浏览器窗口就没有反应，windows提示未响应

**Comment by sylingd** [comment]
我自己测试是没有这个问题的。
我在尝试收集更多资料，寻找复现问题的方法

**Comment by kkren** [comment]
如果有什么log可以提供帮助的话请告诉我

**Comment by sylingd** [comment]
尝试了修复，但是似乎不是我能修复的……

**Comment by sylingd** [comment]
经测试，只要规则是以`(.*)`、`(.+)`这一类通配符开头的正则，就会卡住浏览器，但是单独在console里执行则不会。暂不清楚此原因。目前修复办法为暂时移除此类规则
