### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#29]
1) Clicking 'X' of the Group entity doesn't do anything. Also since this is deleting a whole group of rules it should have a 'Are you sure?' dialog/popup.

2) When importing rules all the rules are placed in 'Ungrouped'. They should be exported with their relevant group names and placed in their respectively named groups when imported.

**Comment by sylingd** [comment]
1. I tested it, it works well. Delete a group won't delete rules in this group, it will move them to the "Ungrouped" group.

2. Header Editor cannot detect which group you want to put them in

**Comment by grenzor** [comment]
1. I see, I misunderstood this function as removing rules.

2. Is it not possible add the ability to export the rules with the group names so it can be imported back to the groups? It's a little bit of a hassle to import all as ungrouped and manually move back the rules to their named groups.

**Comment by sylingd** [comment]
Add a button to select group when import rules
It have some little bugs but I don't want to fix it because I'm planning a new theme.
