### ISSUE TITLE
请教一下，是我设置有问题吗？

### ISSUE THREAD

**Issue by YandLiu** [FirefoxBar/HeaderEditor#3]
Firefox 55.0 空白配置
扩展中只加入了如下规则
![2017-08-10_101825](https://user-images.githubusercontent.com/26127104/29151653-5c002594-7db5-11e7-8b45-ab9ee5aa4d10.png)

但是在[此页面](http://bbs.kafan.cn/forum.php?mod=viewthread&tid=1776525&page=2#pid32904567)测试时，发现请求头并没有更改，而我用Mason改请求头是成功的，不明白哪里有问题
![2017-08-10_102145](https://user-images.githubusercontent.com/26127104/29151753-df3ed018-7db5-11e7-8424-4f45374f8c32.png)

**Comment by sylingd** [comment]
比较奇怪，不知道Mozilla改了什么。我自己测试，53正常，57不正常。我再调试看看

**Comment by sylingd** [comment]
1.0.3已修复此问题
