### ISSUE TITLE
Change timestamp to human readable format

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#32]
Timestamp is added to backup file but it is not in a format that humans can read.
Can it be changed to something like: `headereditor-2017-10-10_12.00.00.txt`

**Comment by sylingd** [comment]
Added [https://github.com/FirefoxBar/HeaderEditor/commit/d0fdd8ea015073e7c503720c4c0c3da1ef978da8](https://github.com/FirefoxBar/HeaderEditor/commit/d0fdd8ea015073e7c503720c4c0c3da1ef978da8)

**Comment by grenzor** [comment]
Just tried, works fine except when it is 12am it shows up as something like `HE-2017-11-11_0.22.15.json`. Notice also the individual group exports still exports using old timestamp method.

Also minor thing but is it possible to keep the export name as "headereditor-2017-10-10_12.00.00.json" instead "HE-2017-10-10_12.00.00.json"? I find that makes it a little easier when searching for a backup file using keyword

**Comment by sylingd** [comment]
I think "headereditor" is too long...

**Comment by grenzor** [comment]
I personally think even though it is a little long it is ok but it's your choice.

Also, for the individual group exports if you can append the group name it will be good as all backups have same name. So like "HE-2017-10-10_12.00.00-groupname.json"
