### ISSUE TITLE
反馈：豆瓣去跳转规则会造成页面错误

### ISSUE THREAD

**Issue by yulelong** [FirefoxBar/HeaderEditor#33]
例如这个链接：
https://www.douban.com/search?q=逍遥法外

第一个结果是：
https://www.douban.com/link2/?url=https://movie.douban.com/subject/26973756/&query=逍遥法外&cat_id=1002&type=search&pos=0
去跳转之后成了：
https://movie.douban.com/subject/26973756/&query=逍遥法外&cat_id=1002&type=search&pos=0
直接在地址栏输以上地址豆瓣会报错。不去跳转就不会。锅是豆瓣的，扩展本身没有问题。

**Comment by sylingd** [comment]
这是规则问题
可以使用类似`url=(.*?)&(.*)`的正则，只取出`url=`后、`&`符号前的URL
