### ISSUE TITLE
Latest version sometimes rules not taking effect

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#34]
In the latest version some of my rules are not taking effect. Not sure if it's reproducible reliably.

Went back to 2.3.3 and it works as intended so I'm assuming something might have broke in the latest update.

**Comment by sylingd** [comment]
Please give me more informations about it, such as which rules have broke.
If all rules are broken, please tell me what did you do, how to reproduct it.

**Comment by grenzor** [comment]
Example rule:
Modify response headers, regexp `https:\/\/en.wikipedia\.org(?:\/.*)?$`, normal, header name `set-cookie` header value leave blank.

In 2.3.3 it does not let site set cookies but in 2.3.4 cookies are still set

**Comment by danielvijge** [comment]
I also see this behaviour. I have a general rule that adds a request header to some domains (based on regex). Some resources (JS/CSS/images) will get the extra header, whilst some don't. It appears to be random which ones get it, and which ones don't.
Reverting back to 2.3.3 solves it completely.

**Comment by danielvijge** [comment]
Here a test case. Visit www.exampe.com, the request header sometimes has the X-Test-Header, sometimes not. This was tested on Firefox 57 (release candidate, no beta number)
<img width="880" alt="screen shot 2017-11-10 at 15 59 26" src="https://user-images.githubusercontent.com/1246723/32664125-98aa7f94-c630-11e7-8ae2-12dfc1624b85.png">

**Comment by sylingd** [comment]
I have reproduced it

**Comment by ivysrono** [comment]
2.3.4 +1
2.3.5 fixed
