### ISSUE TITLE
【功能请求】是否可以修改火狐下载程序的header

### ISSUE THREAD

**Issue by Mapaler** [FirefoxBar/HeaderEditor#35]
photobucket网站的外链图片最初是通过refferer来控制是否获取真实图片的。
但是现在升级了，是通过检测Accept的值来决定是否返回真实图片的。
* 能看到图片的网址  
http://pad.skyozora.com/pets/3994
* 图片外链地址  
http://i1296.photobucket.com/albums/ag18/skyozora/pets_pic2/3994_zpsbj2phekb.png

火狐设置里`image.http.accept`的值是`*/*`，所以`<img>`标签内的图片可以正常获取到图，但是`network.http.accept.default`的值是`text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`，如果直接访问图片地址，请求头的值是后者，于是服务器会返回302重定向到photobucket的网页。

用 **Header Editor** 扩展修改`i1296.photobucket.com`域名的`Accept`为`*/*`后，浏览器访问图片网址可以正常获得图片了。但是使用右键另存为，下载下来的还是重定向的网页。
Fidder测试发现 **Header Editor** 的修改似乎对下载程序无效，下载程序的http请求仍然是`network.http.accept.default`的值。

我后来只有手动修改`network.http.accept.default`为`*/*`才下载成功。
<hr>

我就想知道， **Header Editor** 扩展的规则能否影响到下载程序。

**Comment by sylingd** [comment]
如果现有无法实现，就代表WE没有此权限
实际上WE权限很低。对于浏览器本身发起的请求（例如浏览器自带的同步功能发起的请求）都无法修改
