### ISSUE TITLE
能否添加Microsoft Edge浏览器支持？

### ISSUE THREAD

**Issue by MephistoSatanDevil** [FirefoxBar/HeaderEditor#38]
Edge浏览器能否也支持一下呢？谢谢。

**Comment by lychichem** [comment]
添加是有可能做到的，但限于edge的扩展政策，普通开发者基本无法将扩展上架到ms商店，用加载的方式每次浏览器打开时都要重新加载而且会给个提示，很烦

发送自我的iPhone

在 2017年11月17日，05:48，MephistoSatanDevil <notifications@github.com<mailto:notifications@github.com>> 写道：


Edge浏览器能否也支持一下呢？谢谢。

**Comment by sylingd** [comment]
技术上是可行的，但是ms开发者认证需要300元，而且也不清楚有没有其他限制，因为目前看到的扩展数量实在很少

**Comment by lychichem** [comment]
我知道的情况是ms只允许非常有名的扩展的开发者提交扩展，一般小开发者想提交根本不鸟你的

发送自我的iPhone

在 2017年11月17日，07:47，泷涯 <notifications@github.com<mailto:notifications@github.com>> 写道：


技术上是可行的，但是ms开发者认证需要300元，而且也不清楚有没有其他限制，因为目前看到的扩展数量实在很少

**Comment by MephistoSatanDevil** [comment]
昨天试着自己往上移植，但是规则列表显示不出来，并且加载规则后貌似不能完全生效，不知什么地方错了。其实用加载方式也不是不可以，提示看起来并没有那么恼火。
