### ISSUE TITLE
Thanks for this little gem.

### ISSUE THREAD

**Issue by mikhoul** [FirefoxBar/HeaderEditor#4]
Hi,

I found your addon while I was browsing Github to see if somebody had made new addons for Firefox.

Strangely I was looking also for something to replace the old Stylish addon that will no longr work after Firefox 56 and I found that your addon was injecting UserStyle with the webext API so it will work after Firefox 56. 

Moreover your addon seem a lot better than Stylish and  Stylus, with the help of Google Translate I've translated and read http://tieba.baidu.com/p/5243145582?pn=1 to know a little more about it.

If  you need translation in French I can translate it in my free time since my native language is french.

I will test it tomorrow importing my styles from Stylish with Firefox 56 and will ask if you agree to Ghack to make a review of your beautiful addon.

**A small hint:** Another Very good addon for Firefox/Chrome I use to edit CSS live  maybe you could add colors swatch "color picker widget" to your editor if it is not already done like here:  http://i.imgur.com/V8c4lOL.png

The code for the color widget is here and it is very easy to integrate with the codemirror editor: https://github.com/easylogic/codemirror-colorpicker

Best Regards :octocat:

**Comment by sylingd** [comment]
It's welcome if you want to translate this extension. You can do anything that does not violate the GPL license, including posting to other sites.
I'm working to add more useful features. If you have any good idea, please tell me, I will thinking about it.
Thank you very much for your support.

**Comment by sylingd** [comment]
You can translate xStyle on [transifex](https://www.transifex.com/sytec/xstyle/) now

**Comment by mikhoul** [comment]
Thanks, I will translate it to french in my spare time 😸  

Regards :octocat:
