### ISSUE TITLE
重定向时，有关"file:///"的都不能正常运作

### ISSUE THREAD

**Issue by AutumnFrost17** [FirefoxBar/HeaderEditor#40]
地址栏里用http访问一个html文件，里面将一个脚本(http)定向到另一个脚本(file)，不生效
地址栏里用file访问一个html文件，里面将一个脚本(http)定向到另一个脚本(http)，不生效
地址栏里用http访问一个html文件，里面将一个脚本(http)定向到另一个脚本(http)，生效

然而FF57前我用mason是可以在第一个例子的情况下生效的，第二个没试过

环境: win10家庭中文版16299.64
浏览器: Firefox 57.0 64bit
附加组件版本: Mozilla Add-ons上下的2.3.5
防火墙都关了

**Comment by sylingd** [comment]
火狐的WebExtension对于非http请求（file等）权限非常低，很多页面或者URL根本没有权限。
Mason可以，是因为它使用的技术是传统XUL，传统XUL权限非常高，可以任意读写文件、运行程序。
“新型”的扩展不行，是因为WebExtension方便的同时，也限制的很死，权限很低。
印象中Chrome可以通过选项允许扩展访问本地网址，但是火狐没有这个选项

**Comment by AutumnFrost17** [comment]
谢谢
