### ISSUE TITLE
油猴脚本发起的请求捕获不到

### ISSUE THREAD

**Issue by lybtongji** [FirefoxBar/HeaderEditor#41]
Firefox 56.0.2 中 Greasemonkey 脚本中的 GM_xmlhttpRequest() 请求貌似捕获不到。用 mason 是可以捕获请求。

**Comment by sylingd** [comment]
WebExtension权限问题，HE无权修改其他扩展发起的请求

**Comment by lybtongji** [comment]
这样啊，先等等看 Firefox 后面会不会开放权限

**Comment by sylingd** [comment]
因为安全问题，多半是不会开放的
