### ISSUE TITLE
其他模式增加和redirect一样的下方快速test

### ISSUE THREAD

**Issue by fireattack** [FirefoxBar/HeaderEditor#42]
例如这个：

>正则表达式为`http://a(\d+).qpic.cn/psb`，修改Referer为`http://qzone.qq.com`

也会匹配到`http://a123xqpic.cn/psb`，不安全

另外求两个feature：
1 通配符模式，对于某些特别简单的匹配，用regex太啰嗦了
2 其他模式增加和redirect一样的下方快速test（返回`true`或`false`）

**Comment by sylingd** [comment]
其实wiki中的东西只是个示例，规则不作维护。打算有空进行整理，将这部分精简掉，只留下少数几个示例
通配符不打算，因为最简单的匹配正则表达式也很简单。
test这个功能有考虑

**Comment by sylingd** [comment]
[Added](https://github.com/FirefoxBar/HeaderEditor/commit/0832562da25d71faf23451d1e93e98bf2f97f552)
