### ISSUE TITLE
Thanks... and blocking ETags :)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [FirefoxBar/HeaderEditor#43]
Hi, I just want to say thank you for this extension :kiss: I'm part of a group of people who for the last three years have been building a privacy, anti-tracking, anti-fingerprinting etc user.js for Firefox (obviously there is more outside the browser level that can be done, but that is the project's scope).

For a while it has really bothered me that Firefox no longer fully clears the cache. It used to be that you could go Ctrl-Shift-Del and clear `Cache` and it would eliminate any `ETags` - you will find lots of olderer forum discussions and articles where this was proposed. The other way was to disable both disk and memory cache. I have always had disk cache off, but left RAM being used. This still retained the ETag.

Thanks to your extension and [this rule](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.4-Header-Editor), everything is as peachy as we can get it :+1:  There is still a risk of Last-Modified being used as a tracking mechanism for now.

The above link contains test sites for those interested

**Comment by sylingd** [comment]
Thank you.
Maybe you should notice that Chrome and Firefox is different when you try to modify a header to blank. Firefox will remove it, but Chrome will keep it and set it to blank.
If you have any questions, it's welcome to submit

**Comment by Thorin-Oakenpants** [comment]
FYI: https://www.ghacks.net/2017/12/09/a-solution-to-etag-tracking-in-firefox/

I hope you get an uptick in users and more help with translations & testing

**Comment by sylingd** [comment]
I aslo hope so, thank you

**Comment by Thorin-Oakenpants** [comment]
Feel free to close this when you want .. maybe leave it open for visitors to see the Etag bit for a while, up to you :)
