### ISSUE TITLE
use .toLowerCase when comparing header names

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [FirefoxBar/HeaderEditor#45]
from [this](https://github.com/ghacksuserjs/ghacks-user.js/issues/179#issuecomment-350285399) comment

> The code doesn't use .toLowerCase to compare headers but I think existing headers are now always lowercase, meaning you need use lowercase when you want to **remove** (=use an empty value for it) a certain header. BUT if you want to **add** one you should probably use the correct casing, fe. if you always want to add a Referer Header, name it 'Referer' not 'referer' or you might make yourself pretty unique because nobody else sends a lowercase referer header!

**Comment by sylingd** [comment]
I need to collect more information and consider its necessity

**Comment by sylingd** [comment]
Added.
[RFC 2616](https://tools.ietf.org/html/rfc2616.html#section-4.2) says:

> Each header field consists
   of a name followed by a colon (":") and the field value. Field names
   are case-insensitive.

**Comment by crssi** [comment]
Do I understand correctly that instead of this code:
``` js
for (let a in val) {
	if (val[a].name.toLowerCase() === 'user-agent') {...
```

we can now simplify (get rid of `.toLowerCase()` part): 
``` js
for (let a in val) {
	if (val[a].name === 'user-agent') {...
```

?

**Comment by sylingd** [comment]
@crssi No, I think custom functions should have more precise control, so I'm not going to pass lowercase headers to custom functions

**Comment by crssi** [comment]
Thank you

**Comment by sylingd** [comment]
@crssi Yes

**Comment by crssi** [comment]
A speed of light you are in responsive terms. :smile: :+1: Thank you.
I might see a bug then.
If the value entered into `Header name` is not lowercase then we never get a match.

For example create a new rule:
Rule type: Modify the response header
Match type: All
Execute type: normal
Header name: **ETag**
Header value: -none-

Result: header ETag **is not cleared**, which is not expected.

Then edit this rule:
Rule type: Modify the response header
Match type: All
Execute type: normal
Header name: **etag**
Header value: -none-

Result: header ETag **is cleared** as it should be.

Can you correct the code in that case to take a lowercase of the value entered in the `Header name`?

Thank you and cheers

**Comment by sylingd** [comment]
@crssi In my memory, I should have dealt with it. I will check it later.
