### ISSUE TITLE
dashboard icons: browser.display.use_document_fonts & material design icons

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [FirefoxBar/HeaderEditor#46]
`Exploer` => `Export`

What icon font are you using, I seem to have some broken glyphs in 3.0.1 - I'm not even getting the usual tofu/hexidecimal-rectangular icon when a PUA is not mapped

![he-dashboard](https://user-images.githubusercontent.com/16656956/33892848-c32ef96e-dfbe-11e7-9c16-bd6f00babc0e.png)

This would be the first extension that has ever done this to me

**Comment by sylingd** [comment]
I'm sorry for my negligence. The icon is [google/material-design-icons](https://github.com/google/material-design-icons)

**Comment by Thorin-Oakenpants** [comment]
> I'm sorry for my negligence
No negligence here :) You're doing an awesome job. 

ON the material design icons github page they say
> it is generally better to link to the web font hosted on Google Fonts

I see the icons are local under `..\third-party\material-design-icons` - so I assume that no calls are being made to google, right? (I am not a developer)

The problem is caused by `browser.display.use_document_fonts`=0. This is the setting under
```
 * [SETTING-56+] Options>General>Language and Appearance>Advanced>Allow pages to choose...
 * [SETTING-ESR] Options>Content>Font & Colors>Advanced>Allow pages to choose...
```

I could probably live with the icons displaying text (a lot of them are truncated), and that is what I will have to do because I cannot allow documents fonts - doing so destroys my font fingerprinting defense and causes very high entropy,

Other extensions load various icon fonts just fine. I am not a developer, so please excuse my ignorance on this, but there must be a way for this to work with `browser.display.use_document_fonts`=0

@gorhill Sorry for taking up your time, but uBo and uM use icon fonts no problems. Could you please have a quick look at this, or explain in tech terms how you implement it. For all I know its not the implementation but how Firefox determines that Material design is not a glyph. It's beyond my knowledge, so would appreciate some help

**Comment by gorhill** [comment]
@Thorin-Oakenpants Looks to me you are afflicted by something similar to <https://github.com/gorhill/uBlock/issues/2878>. My understanding: `use_document_fonts=0` means _"do no use document fonts, except when a code point is not available in the system fonts"_. However, somehow, your system fonts contains glyphs for code points which are used by the font-based icons -- hence the browser ends up using a glyph from your system font rather than the one from the icon font.

**Comment by Thorin-Oakenpants** [comment]
@gorhill - nope, I am getting NO icons, not even `tofu` <sup>1</sup> (see first pic, unless tofu means I get some text displayed instead). I have no trouble getting your icon fonts, or anyone else's in various panels, etc. Back before mozilla added `gfx.downloadable_fonts.enabled` in FF41, there was the issue that uBo/uM icon fonts were blocked. That was years ago.

So it's something else, either:
- material design icons and/or their PUA's are not being detected as glyphs/icon-fonts and covered under `gfx.downloadable_fonts.enabled` (which I have as true) and thus they fall under `use_document_fonts` (which I have as false)
- the implementation in this extension differs from everything else that I have that shows icon fonts

<sup>1</sup> https://en.wikipedia.org/wiki/Tofu_(disambiguation)
> Tofu, or tofu character, Internet slang for substitute character, the empty box or other marker shown in place of an undisplayable code point (character) in a computer font (typeface)

**Comment by fancytenseletters** [comment]
I'm also affected by this issue.

**Comment by gorhill** [comment]
Ok, I had to dig and today-I-learned about _ligatures_. Excerpt from the [Material Fonts documentation](http://google.github.io/material-design-icons/#what-are-material-icons-):

> This example uses a typographic feature called ligatures, which allows rendering of an icon glyph simply by using its textual name. The replacement is done automatically by the web browser and provides more readable code than the equivalent numeric character reference.

So no code point is used in the HTML source, but rather a symbol name, and from this symbol name the browser is able to fetch the proper icon in the font. I suppose if the browser can't find the icon from its name, it just does not render anything -- as opposed when a code point is declared, the browser will use tofu if the code point does not exist.

**Comment by sylingd** [comment]
I found a solution. If you set `use_document_fonts=0`, Firefox will make the default font-family to `sans-serif, "Material Icons"`, because the word "list" can be rendered by sans-serif correctly, the `"Material Icons"` will have no effect.
So, use `<i class="material-icons">&#xE896;</i>` to replace `<i class="material-icons">list</i>` can solute this problem, because the `&#xE896;` is a special word which can not be rendered by sans-serif correctly, Firefox will use `"Material Icons"` to render it.

**Comment by Thorin-Oakenpants** [comment]
thanks @gorhill for the digging (now I know about ligatures as well) and @sylingd for the workaround

For the record: when you set/change `use_document_fonts`, it does not "change" your 3 default fonts, which you can do independently. The default fonts (`.serif`, `.sand-serif`, `.monospace`) are different per OS. And on top of that they will different on your language set (`western`, `cyrillic` etc)

Here's hoping the fix works universally :)

**Comment by sylingd** [comment]
[Added](https://github.com/FirefoxBar/HeaderEditor/commit/90181c1ceafd658a66bf9e232a78d6a687efad01)

**Comment by Thorin-Oakenpants** [comment]
Yup, I noticed: got this repo starred. Just been waiting for AMO to update to a new release when you're ready :)

**Comment by Thorin-Oakenpants** [comment]
Just updated to 3.0.3 and can confirm on WIndows with `browser.display.use_document_fonts`=`0`, the icon-fonts/ligatures look great - thanks :+1:

**Comment by Thorin-Oakenpants** [comment]
@sylingd I think you have a typo: not worth a new issue

`Add "Add anti-anti-theif-link" to right-click menu` .. thief is spelled with an `ie`, not `ei`

**Comment by fancytenseletters** [comment]
@Thorin-Oakenpants BTW what that option does?

**Comment by Thorin-Oakenpants** [comment]
@fancytenseletters - that is the pref behind:
 * [SETTING-56+] Options>General>Language and Appearance>Advanced>Allow pages to choose...
 * [SETTING-ESR] Options>Content>Font & Colors>Advanced>Allow pages to choose...

0=unchecked (so you limit fonts to the three families specified above)
1=default

This is for some font fingerprinting mitigation

**Comment by fancytenseletters** [comment]
Nah, I meant what `anti-anti-theif-link` option do. :smile:

**Comment by sylingd** [comment]
@fancytenseletters Don't like Google Photos, some online photo album doesn't allow users upload photos to it and using this photo in other websites(for example, someone's personal blog) because this will consume their bandwidth. It called "anti-thief-link"

**Comment by Thorin-Oakenpants** [comment]
^^ oh, so "hot-linking" then: https://en.wikipedia.org/wiki/Hot_linking . I wondered what it meant as well. The checkbox is just to add a menu item AFAIK, so I didn't bother to dig any further :)

**Comment by sylingd** [comment]
Oh I didn't know it called "hot-linking", I will correct it

**Comment by Thorin-Oakenpants** [comment]
That's just what I've always known it as - because... search google images for "hotlinking" or "hot linking" and you'll see some of the images sites use to serve up in lieu of ...  back in the good old days of slow and costly bandwidth

The wiki link is an alias - the actual technical term according to them is "Inline Linking", but I don't think it's a very catchy name :)

**Comment by Maryse47** [comment]
@sylingd after 4.0.0 release this prob;em is back.

**Comment by sylingd** [comment]
@Maryse47 Yes, I use a lot of new components and I am thinking about how to solve this problem.

**Comment by sylingd** [comment]
Because of the many new components used, the old fixes are no longer valid. I have some new ideas, but they are more complicated, so the repair time for this problem may be longer.
