### ISSUE TITLE
Can't disable rules and execute type is always set to normal

### ISSUE THREAD

**Issue by fsproede** [FirefoxBar/HeaderEditor#47]
When I disable a rule it is still enabled. When I edit a disabled rule it is enabled after saving.

When I edit a rule with a custom function, the execute type is always set back to "normal".

The bugs exists in FF extension 3.0.1 and Chrome extension 3.0.0

**Comment by sylingd** [comment]
I'm sorry for my negligence. I have fixed them up. The next release will be released in the near future
