### ISSUE TITLE
Bugs with new layout

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#49]
1) After rule is saved, you can't edit Match type or Rule type, it is all whited out. 

2) If you edit a rule and then save it you cannot see changes you made to that rule on the page. You have to refresh the page to see the changes to the rule.

3) If you import a certain group's rules (example, 3rd group) only the first rule of that group is imported into it while the rest of the rules are imported to another group (example, 2nd group).

4) Pink buttons (batch operation + add rule) are a little too big. They can block the `^` icon of the group when scrolling. Maybe it's better idea to have them as tabs in the top blue bar (with Rules List + Export/Import).

5) Adding hover tooltips to the buttons will be helpful as it can be confusing what each button does.

**Comment by sylingd** [comment]
I have fixed bug 1 and 2, but I can not reproduce bug 3, do you means this feature? I tested it and it works well.
![tim 20171213180101](https://user-images.githubusercontent.com/5326684/33933120-be0aa7f0-e02f-11e7-8517-a30d12ef2ddb.png)

**Comment by grenzor** [comment]
I just tried again and it imports properly, don't know why it didn't before. If I reproduce again I'll post but for now it's ok.

**Comment by sylingd** [comment]
For the problem 4, I think of a new solution, you can click the title to show or hide a group, do you have any better idea?
The add button can move to the top but the batch button can not, so I think it is not a good idea

**Comment by fancytenseletters** [comment]
6. Text in "Match rules" isn't wrapped so even very long rules are displayed in single line and you have to scroll horizontally to see next columns like "Match type", "Action" etc.

**Comment by Qwash** [comment]
@sylingd it would be better if I can save the state of the hidden groups and keep them hidden

**Comment by grenzor** [comment]
@sylingd I think clicking the title to hide/show group is a good solution for problem 4
