### ISSUE TITLE
Rearrange groups and rules

### ISSUE THREAD

**Issue by Qwash** [FirefoxBar/HeaderEditor#50]
I would like to be able to rearrange groups and rules
Also, when you group all rules, the default group "Ungrouped" stay visible and can't be deleted

**Comment by sylingd** [comment]
Of course, because if you delete a group, all rules in this group will move  to "Ungrouped", so it can not be deleted

**Comment by grenzor** [comment]
I think rearrange groups and rules is a good idea (so users can manually move them around or click "Name" to sort alphabetically within the group). 

Also would be good if we are able to change group name after it's created (currently you have to create a new group just to change its name).

**Comment by Qwash** [comment]
it can be deleted when empty and recreated again in the case you mentioned

**Comment by sylingd** [comment]
Maybe I can add a option named "hide empty group"

**Comment by sylingd** [comment]
[Added](https://github.com/FirefoxBar/HeaderEditor/commit/062aac03a7f5ffd70a59dd291ab2c21f27d8412a)

**Comment by Qwash** [comment]
Latest update removed the "hide empty group" option

**Comment by sylingd** [comment]
@Qwash Yes, because groups is determined by rules in new version, so the empty group will be removed automaticly, except for "ungrouped"

**Comment by sylingd** [comment]
When I made this change, I did not consider about this problem, I will try another way to solve this problem in the next version.

**Comment by Qwash** [comment]
OK, thanks :)
