### ISSUE TITLE
导出的规则文件没有保存分组名信息

### ISSUE THREAD

**Issue by dupontjoy** [FirefoxBar/HeaderEditor#51]
如果不保存分组信息的话, 导规则文件时又会全部到未分组里去了

**Comment by sylingd** [comment]
并不打算……因为如果要将分组一并导出，需求上来说并不是十分必要，但是工作量却是比较大的。综合而论我不太愿意做这个功能

**Comment by ivysrono** [comment]
需要+1
我维护了个规则项目，如果能将分组一并导出，我就可以合并多条规则了。

**Comment by dupontjoy** [comment]
@sylingd 
因为不保存分组信息的话, 就算把每个分组都单独导出一份配置文件, 再次导入时还是会都到"未分组"里去

**Comment by sylingd** [comment]
导入的时候可以手动选择分组
