### ISSUE TITLE
能否提供更为详细的使用说明

### ISSUE THREAD

**Issue by tumuyan** [FirefoxBar/HeaderEditor#52]
这个扩展很棒，但是我不会用？
wiki太过简洁，软件界面对于不熟悉JavaScript的人也不友好。

1. 我想在原有的request head基础上添加“{"name":"os","value":"android"},{"name":"X-Auth-Token","value":"d793c5ab-99a6"}”这样批量性的键值，需要怎么写？
2. 如果我想从head移除{"name":"os","value":"android"},需要怎么写？
3. 怎么获取head中包含的键的数量？

谢谢

**Comment by tumuyan** [comment]
另外我在使用https://addons.mozilla.org/firefox/addon/decentraleyes  
header editor理论上也能做到decentraleyes 的功能?
希望header editor增加这样的功能：
允许用户保存一个文件，可以重定向互联网资源到扩展内的这个本地文件。

**Comment by sylingd** [comment]
wiki将会进行整理。但我想知道用户想要从wiki中得到什么信息？
WE没有权限读写本地文件，因此我能想到的方法是比价麻烦的。同时，HE的目的是用于修改头信息，因此也不打算增加太多关系不大的功能

**Comment by tumuyan** [comment]
那么能否就我遇到的困难先帮忙解答呢？
1.我想在原有的request head基础上添加“{"name":"os","value":"android"},{"name":"X-Auth-Token","value":"d793c5ab-99a6"}”等等这样批量性的键值，需要怎么写自定义函数？
2.如果我想从head移除{"name":"os","value":"android"},需要怎么写？
3.如果我想添加uinx timestamp到head中，那么应该是可以使用自定义函数Math.round(new Date().getTime())做赋值的，对吗?

>

关于文件这一点，我觉得可以以其他形式（非文件）保存到浏览器storage中，拦截请求并把这数据直接取回就可以了？

**Comment by sylingd** [comment]
1.需要自定义函数，代码类似：
```
val.push({"name":"os","value":"android"});
val.push({"name":"X-Auth-Token","value":"d793c5ab-99a6"});
```
2.目前发现移除header在Chrome下面会有BUG
```
for (let a in val) {
	if (val[a].name.toLowerCase() === 'name' && val[a].value === 'android') {
		delete val[a];
		break;
	}
}
```
3.这样：
```
val.push({"name":"timestamp","value":Math.round(new Date().getTime())});
```

**Comment by sylingd** [comment]
关于另一个问题，目前我倒是有一些想法，但是说实话不适合做到这个扩展里面

**Comment by tumuyan** [comment]
非常感谢你的说明。但是我用val.push({"name":"timestamp","value":Math.round(new Date().getTime())});并没有生效，似乎出现了错误。需要帮忙确认一下原因？
1.首先al.push({"name":"timestamp","value":1+1});是正确的。
2.浏览器也可以执行JavaScript:alert(Math.round(new Date().getTime()));

**Comment by sylingd** [comment]
使用`val.push({"name": "timestamp", "value": Math.round(new Date().getTime()).toString()});`就行了

**Comment by tumuyan** [comment]
已经OK。由于有自定义函数和方便的导入导出功能，he毫无疑问是最好用的header修改扩展。
希望可以把val.push({"name": "timestamp", "value": Math.round(new Date().getTime()).toString()});作为自定义函数的范例放入wiki。
另外有没有可以像he一样修改请求头的proxy server软件？

**Comment by sylingd** [comment]
proxy server指的是？

**Comment by tumuyan** [comment]
额 类似于这个扩展，但是本质是一个本地代理服务器。
所有使用这个代理服务器的HTTP请求头都会被按照规则修改

**Comment by sylingd** [comment]
不是很清楚有没有这种东西……
