### ISSUE TITLE
Issue with group button in batch mode

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#56]
When using batch mode, the group button can choose a group but doesn't do anything. Is this supposed to choose all rules in the group?

**Comment by sylingd** [comment]
You can select or unselect a group by click here
![2017-12-20_154642](https://user-images.githubusercontent.com/5326684/34196550-85ad63c0-e59d-11e7-9044-74ec55e1dffe.png)

**Comment by grenzor** [comment]
Ah ok, got it.

**Comment by grenzor** [comment]
Ah ok, got it.

**Comment by grenzor** [comment]
Ah ok, got it.
