### ISSUE TITLE
如何取消在图片上右键“添加反盗链规则”此选项？

### ISSUE THREAD

**Issue by operammm** [FirefoxBar/HeaderEditor#57]
在图片上右键会出现“添加反盗链规则”这一项，希望可以添加取消右键菜单的选项。
此外，建议在wiki的常见功能示例中添加强制http为https的示例。
如果使用说明的常见功能示例再多一些就好了。
像我一样的照葫芦画瓢的非专业玩家也能用起来更方便一些～谢谢啦。

先隐藏掉了……愿未来能看到内置的开关选项。
#headereditor-amo_addon_firefoxcn_net_add-anti-theft-link {display:none !important;}

**Comment by sylingd** [comment]
暂时不可以，有计划增加选项功能

**Comment by operammm** [comment]
收到。
希望wiki里的常见功能示例能多写几条。谢谢。

**Comment by sylingd** [comment]
[Added](https://github.com/FirefoxBar/HeaderEditor/commit/151fd900447eac3c219183a47ebc06f7b29aac5b)
