### ISSUE TITLE
测试功能有瑕疵和扩展主页面显示小建议

### ISSUE THREAD

**Issue by HeJiaJunPan** [FirefoxBar/HeaderEditor#58]
我只测试了重定向请求+正则表达式，火狐57，HeaderEditor3.0.2
1.同样的规则，同样的示例链接，第一次测试显示不匹配（在redirector扩展中测试匹配），只能退出当前编辑页面，重新编辑规则，测试后显示匹配。这种测试结果bug会否影响到扩展的重定向功能？

2.扩展主页面，如果“匹配规则”这一栏规则太长，会遮挡后面的编辑、删除等功能按钮。虽然分组有水平滚动条，但滚动条保持在分组底部，分组内规则多的话，依然影响操作。
能否限制扩展主页面每栏的长度，让按钮完整出现在视野里，不用拖动水平滚动条？

**Comment by sylingd** [comment]
1.不会影响。不过是否有稳定重现的方法？我看看是怎么回事
2.会在接下来改进
