### ISSUE TITLE
希望加入修改 response 数据的功能

### ISSUE THREAD

**Issue by ghcsd** [FirefoxBar/HeaderEditor#60]
相关API
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/StreamFilter

**Comment by ghcsd** [comment]
https://github.com/gorhill/uBlock/releases/tag/1.14.23b10
刚刚 uBlock 新增支持响应后文档解析前屏蔽（删除）元素的功能正是利用该API。
https://github.com/gorhill/uBlock/issues/3069

**Comment by sylingd** [comment]
考虑中

**Comment by machsix** [comment]
同需要，最好能提供修改x-frame-option的功能，chrome有插件https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe，但是火狐的https://addons.mozilla.org/en-US/firefox/addon/ignore-x-frame-options/不能用于新版了。。
有一个开源的代码但是看不懂:(
https://github.com/arantius/nbfod

**Comment by sylingd** [comment]
因此API为Firefox专有，且并不常用，故暂不编写
