### ISSUE TITLE
奇怪的bug：修改规则2会把UI更新到规则1上去

### ISSUE THREAD

**Issue by fireattack** [FirefoxBar/HeaderEditor#62]
感觉是数据库有问题，我直接导出规则再导入无法重现，但是用我现在这个profile就可以

重现用profile：

[profile.zip](https://github.com/FirefoxBar/HeaderEditor/files/1609593/profile.zip)

重现步骤：

1. 用上述附件的内容覆盖一个测试用的profile （删除别的内容先）

2. 打开 HE
3. 修改第二个规则，然后修改名称，点save
4. Save之后，应该会自动返回列表，会发现被改的是第一个……

刷新之后恢复正常

下面这个GIF说明了这个BUG

![heh3](https://user-images.githubusercontent.com/4130991/34647950-02adbbc0-f356-11e7-8827-a83b94f9d770.gif)

**Comment by sylingd** [comment]
刷新后正常的话，那应该只是一点小问题，我有空检查一下
