### ISSUE TITLE
删除pref.js "extensions.webextensions.uuids" 字段会导致丢失所有规则

### ISSUE THREAD

**Issue by fireattack** [FirefoxBar/HeaderEditor#63]
如题，感觉不应该有影响

随便试了几个其他的extension没有这种问题

**Comment by sylingd** [comment]
不太明白这个东西到底是干嘛的

**Comment by fireattack** [comment]
打扰一下 @yfdyh000 有idea吗？

**Comment by yfdyh000** [comment]
能重现。
https://discourse.mozilla.org/t/constant-or-well-known-mox-extension-uuid-for-webextension/9701

**Comment by sylingd** [comment]
我简单翻译一下，每个扩展安装时都有唯一的UUID，你把这玩意儿删掉了，就相当于你卸载并重新安装这个扩展。规则储存于IndexedDB，此DB依赖于URL。因此UUID变化了就读取不到原来的数据库了。
其他扩展可以读取，可能是因为它们使用的同步API进行储存，同步API可以在卸载重装后恢复数据，但是大小限制100KB
