### ISSUE TITLE
Export function not working on Android

### ISSUE THREAD

**Issue by Kusresa** [FirefoxBar/HeaderEditor#64]
I tried to use the Export function on Android but when clicked nothing happens. Import function works fine as far as I checked.

**Comment by sylingd** [comment]
I will check it later

**Comment by Kusresa** [comment]
Hi @sylingd, did you get a chance to check this?

**Comment by sylingd** [comment]
I have checked before and tried some ways. But Firefox on Android has some weird problems that make it impossible for me to debug it.

**Comment by sylingd** [comment]
Fixed
