### ISSUE TITLE
Wrap "Match rules" text in addon config menu

### ISSUE THREAD

**Issue by fancytenseletters** [FirefoxBar/HeaderEditor#65]
Currently "Match rules" line text isn't wrapped in new layout so having some long regex (I have several hundreds chars) means it's hard to navigate as you have to scroll horizontally to use any of available options.

I already mentioned this in https://github.com/FirefoxBar/HeaderEditor/issues/49#issuecomment-351425632

**Comment by sylingd** [comment]
Improvements about this are already planned.
Related issue: #58

**Comment by fancytenseletters** [comment]
Thanks, I wasn't aware of this as I can't read Mandarin. I'm sorry.
