### ISSUE TITLE
all rules missing from UI

### ISSUE THREAD

**Issue by atomGit** [FirefoxBar/HeaderEditor#68]
no idea what caused this, but all of my rules have disappeared from the UI - the rules still exist when i export them to the json file, but they do not appear in the UI, even when imported from the json file

contents of the exported json file:

`{"request":[{"enable":1,"name":"clean image links","ruleType":"redirect","matchType":"regexp","pattern":"(https?://.*\\.)(jpg|jpeg|gif|png|svg).*","exclude":"","isFunction":false,"action":"redirect","to":"$1$2","id":1,"_reg":{}},{"enable":1,"name":"[bitchute.com] XML feed video embed redirect","ruleType":"redirect","matchType":"regexp","pattern":"https://www.bitchute.com/embed/(.+)","exclude":"","isFunction":false,"action":"redirect","to":"https://www.bitchute.com/video/$1","id":2,"_reg":{}},{"enable":0,"name":"[addons.mozilla.org] clean params","ruleType":"redirect","matchType":"regexp","pattern":"https://addons.mozilla.org/en-US/firefox/addon/(.*)/\\?src=","exclude":"","isFunction":false,"action":"redirect","to":"https://addons.mozilla.org/en-US/firefox/addon/$1/","id":4,"_reg":{}},{"enable":1,"name":"[feeds.feedburner.com] get non-feedburner feed","ruleType":"redirect","matchType":"regexp","pattern":"https?://feeds.feedburner.com/(.+)","exclude":".*feedextinguisher.vltf.org/.*","isFunction":false,"action":"redirect","to":"https://feedextinguisher.vltf.org/extinguish?url=https://feeds.feedburner.com/$1","id":8,"_reg":{},"_exclude":{}}],"sendHeader":[],"receiveHeader":[{"enable":1,"name":"ETAg Removal","ruleType":"modifyReceiveHeader","matchType":"all","pattern":"","exclude":"","isFunction":0,"action":{"name":"etag","value":""},"id":1},{"enable":1,"name":"cache control","ruleType":"modifyReceiveHeader","matchType":"all","pattern":"","exclude":"","isFunction":false,"action":{"name":"Cache-Control","value":"private, only-if-cached, max-age=43200"},"id":2},{"enable":1,"name":"X-Forwarded-For","ruleType":"modifyReceiveHeader","matchType":"all","pattern":"","exclude":"","isFunction":false,"action":{"name":"X-Forwarded-For","value":""},"id":3}]}`

Waterfox 56.0.3
Header Editor 3.0.4 (also tried 3.0.3 and 3.0.2)
Linux

**Comment by sylingd** [comment]
Please press F12 and open "Console" in management page
Is there any error messages in console?

**Comment by atomGit** [comment]
when exactly do you want me to check the console - with a webpage loaded? with the HE UI loaded?

with the HE UI open, there is nothing in the console (i did an F5 refresh to double check)

**Comment by sylingd** [comment]
Maybe you have deleted all groups?
Try to open console, input those codes, then press Enter:
```
localStorage.removeItem("groups");
```

**Comment by atomGit** [comment]
i have not deleted anything - the add-on was working fine, then for some unknown reason all the rules disappeared

i also wonder why the rules i exported can't be imported

i don't understand how or where to run the code you provided

**Comment by sylingd** [comment]
I tested but I can import your export file
![img](http://ww1.sinaimg.cn/large/0060lm7Tly1fnvgljpi2dj30yr0ecjs5.jpg)

**Comment by atomGit** [comment]
i uninstalled HE, restarted FF and reinstalled HE - the tool-bar icon was missing until i reset `extensions.databaseSchema` and restarted FF (i notice this happens often with other add-ons, such as uBlock)

after the restart, i again tried to import the rules i exported prior - when importing rules, they are always displayed in a list as expected before they are saved, but then after they are saved they do not appear in the rules UI - this time when i imported the rules, i clicked the option to group the ungrouped rules and, again, they do not appear in the UI, however [the result](https://imgoat.com/uploads/033ab37c30/79585.png) is slightly different

**Comment by sylingd** [comment]
1. Open management page
2. Press F12, and open "Console"
3. Input `localStorage.removeItem("groups");`
4. Press Enter

![img](http://ww3.sinaimg.cn/large/0060lm7Tly1fnvgvqto21j30jh0imwft.jpg)

If there is any error messages (red background and red text), please take a screenshot, like this:
![im](http://ww2.sinaimg.cn/large/0060lm7Tly1fnvgz8co70j30cu05pq2v.jpg)

**Comment by atomGit** [comment]
i found the problem :) 
the answer is in the [screen-cap](https://imgoat.com/uploads/033ab37c30/79585.png) i provided - on the upper-right is a '^' button used to expand or collapse the rule list and it was collapsed (though i don't recall ever collapsing it)

kind of an embarrassing oversight on my part and i apologize for the trouble :)

sorry for the bother
