### ISSUE TITLE
Import broken

### ISSUE THREAD

**Issue by grenzor** [FirefoxBar/HeaderEditor#69]
Using 3.0.4 and Firefox 58 import is broken. It just keeps showing the circle loading symbol but nothing loads.

Edit: I tried older versions like 3.0.1 and import is broken there too (even though it was working on Firefox 57). I am guessing something broke because of Firefox 58

**Comment by sylingd** [comment]
I tested on Firefox 59 and it works well, please provide the file you want to import

**Comment by grenzor** [comment]
I just removed the addon and reinstalled again and was able to import again. Weird, but think this can be closed for now.
