### ISSUE TITLE
更改响应头的功能无效

### ISSUE THREAD

**Issue by YandLiu** [FirefoxBar/HeaderEditor#7]
64 位 Firefox 55.0.2，已在空白配置下测试

**Comment by sylingd** [comment]
我在Firefox 57下测试，工作正常。能否提供更多信息
![qq 20170818150050](https://user-images.githubusercontent.com/5326684/29447803-2293ca78-8426-11e7-8298-14d6c81f38d7.png)
![qq 20170818150026](https://user-images.githubusercontent.com/5326684/29447809-260dcda2-8426-11e7-8d62-33ac0bb2b813.png)

**Comment by YandLiu** [comment]
用你图上的header测试了一下，确实是更改成功了。
但是从firefox的网络面板里看不到改掉之后的结果，这个issue应该算是误报了，sorry。
![2017-08-18_181844](https://user-images.githubusercontent.com/26127104/29455007-fd7993f0-8441-11e7-8ed3-2b7901068272.png)

![2017-08-18_182115](https://user-images.githubusercontent.com/26127104/29455073-4d54bf80-8442-11e7-9cf3-d93dad516daf.png)
