### ISSUE TITLE
疑似firefox59失效

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/HeaderEditor#70]
Win10 x+4
Firefox 59b3 b4 x64
扩展版本：3.0.4
规则：
https://github.com/ivysrono/HeaderEditorRules/raw/master/anti-anti-leech.json
测试：
https://bbs.kafan.cn/thread-2102542-1-1.html

58下工作正常，59下大部分失效。

**Comment by sylingd** [comment]
实际上，将头设置为字符串不会删除它，不同的浏览器处理方式不一样。
Chrome会将其清空（设置为空字符串）。Firefox旧版将删除它。Firefox新版将不进行处理。
