### ISSUE TITLE
Rule stopped working

### ISSUE THREAD

**Issue by Kusresa** [FirefoxBar/HeaderEditor#71]
Rule type: Modify request header
Match type: Regular expression
Header: Referer
Rule: ^((?!pinterest.com|cnn.com).)*$

Above rule should remove Referer header for all sites except pinterest.com and cnn.com but recently it stopped working. I tested and the rule works on 3.0.2 but stopped working in 3.0.3. 

Firefox version: 59

**Comment by sylingd** [comment]
In fact, set a header to a empty string will not remove it, and different browser have different behaviors.
Chrome will set it to eempty.
Old Firefox will remove it.
New Firefox will do nothing about it.

**Comment by Kusresa** [comment]
Setting header to empty string removes it even in the newest Firefox but I have to use version 3.0.2 of the addon. From my limited testing only 3.0.3 onwards it doesn't remove it

**Comment by sylingd** [comment]
Fixed

**Comment by Kusresa** [comment]
It is working now, thanks
