### ISSUE TITLE
[Feature request] re-order rules

### ISSUE THREAD

**Issue by ecornely** [FirefoxBar/HeaderEditor#72]
When playing with many rules, it would be great to have the opportunity to re-order them.

Drag-drop or movement buttons would be good.

**Comment by sylingd** [comment]
I do not think it is very useful, you can place rules in different groups, and search them by press CTRL+F, but I think it is troublesome to make.

**Comment by vertigo220** [comment]
I would like to second this request. When only have two or three related rules, adding them to a group doesn't do a whole lot, and certainly with a bunch of random rules, it doesn't make sense to add them each to their own group, but it would still be nice to be able to have them in a particular order. Even if manually reordering is too much to add, maybe they could at least be ordered alphabetically. As it is, the ordering seems not only random (it's not alphabetical, doesn't seem to be based on order of creation, and I don't see any other pattern) but it's different at different times (if I disable and re-enable HE, the rules are in one order, but when I close and reopen the rules/options, they're in a different order, and they seem to occasionally, randomly change back and forth). Here's my rules so far (I plan to add more so, while not a big deal now, this will become more important over as I do) in the two different orders they appear:

![image](https://user-images.githubusercontent.com/12024557/40501664-88f4c022-5f56-11e8-8fe1-a682e7ea3ee7.png)
-=============================================================
![image](https://user-images.githubusercontent.com/12024557/40501670-8e5262d6-5f56-11e8-9541-9d5b9a41b0e3.png)
