### ISSUE TITLE
[enhancement] Enable or disable a whole group

### ISSUE THREAD

**Issue by epestela** [FirefoxBar/HeaderEditor#73]
could be usefull to add an enable/disable button on the group bar

**Comment by sylingd** [comment]
You can select or unselect a group by click here
![img](https://user-images.githubusercontent.com/5326684/34196550-85ad63c0-e59d-11e7-9044-74ec55e1dffe.png)
and in batch mode, the second button on the bottom right can enable or disable all selected rules

**Comment by epestela** [comment]
sorry, my mistake :)
