### ISSUE TITLE
Not working in FF Developer and FF Quantum at the same time

### ISSUE THREAD

**Issue by antikpat** [FirefoxBar/HeaderEditor#77]
![notworking](https://user-images.githubusercontent.com/38672792/39157346-12549db4-4720-11e8-97b5-dfffc12f7f19.gif)
1. I had the Add-On installed in FF Developer Edition, it is working fine. I have had it installed for many months now
2. I installed it in FF Quantum (regular FF), I did not have it installed here before
3. Cannot add any new rules through FF Quantum. Rules just don't save. I can add Groups but can't add any new rules.

Please let me know if you have any questions. Thanks.

**Comment by sylingd** [comment]
I have test in nightly 61.0a1(2018-04-21) and it works well. Can you take a screenshot of Console (Press F12) to help me find the reason?

**Comment by antikpat** [comment]
Here are two screenshots, 
This one is when I first open Header Editor in FF Quantum
![image](https://user-images.githubusercontent.com/38672792/39257091-40c0f9b6-4876-11e8-89dd-6e17c5ce16a4.png)

This one is when I try to save a rule
![image](https://user-images.githubusercontent.com/38672792/39257221-a0d7ee5e-4876-11e8-94bd-7199d65a9337.png)
 For the first screenshot, let me know which error you want me to expand

**Comment by sylingd** [comment]
The reason why it not work is HE can not open database. This situation is very strange and rare. I have tried to solve it but failed. It seems that is a Firefox's bug. It can usually be solve by create a new firefox profile
