### ISSUE TITLE
Amazon > Amazon Smile redirect issue

### ISSUE THREAD

**Issue by vertigo220** [FirefoxBar/HeaderEditor#78]
I'm trying to set this to automatically redirect me from www.amazon.com to smile.amazon.com to make purchases but am having trouble. My first thought was to use the cart link (https://www.amazon.com/gp/cart/view.html/ref=nav_cart) and replace the www with smile, but it just gave an error if I wasn't already logged in, so that option was out. I then figured I'd just redirect from that link to smile.amazon.com (vs the whole link with www replaced by smile), and that way if I'm not logged in, I get the login page, and if I am I get the main Amazon Smile page, at which point I could just click the cart again.

While that's an acceptable compromise, I was hoping to do better, and so I figured I could do the redirect when accessing the checkout page, which you have to be signed in for the checkout button to even be available, which would solve that issue. So I set up a regex redirect filter for https://www\.amazon\.com/gp/buy/(.*) to go to https://smile.amazon.com/gp/buy/$1 but it doesn't work when clicking on the checkout button. Once on the checkout page, if I refresh the page it redirects. I tried it with Request Control and Redirector and they both did the same thing as well, though with them if I try to go directly to the checkout URL (https://www.amazon.com/gp/buy/spc/handlers/display.html?hasWorkingJavascript=1) by entering it in the location bar the redirect works, whereas it doesn't with this addon (it's adding &pldnSite=1 at the end and resulting in an error). I suspect the issue is that the checkout button isn't a normal link (hovering over it doesn't provide a link tooltip and right-clicking it doesn't provide any link options) and is probably using javascript. Still, it seems like the redirect should work as soon as the browser receives the address. Any suggestions, or is this just something that won't work? The fact I can't get it to work with any of the three addons leads me to believe that's the case, but it would be nice to get it working.

**Comment by Qwash** [comment]
[Smile@Amazon](https://greasyfork.org/en/scripts/39709-smile-amazon)
[Amazon Smile Redirect](https://greasyfork.org/en/scripts/33073-amazon-smile-redirect)

**Comment by vertigo220** [comment]
Those both do the same thing, which is to say _not_ what I'm trying to do. I can easily use any of these redirect addons to do what those scripts do. The problem is that I _do not_ want it to redirect all Amazon sites to smile.amazon, I only want it to redirect during checkout. And for whatever reason, none of the redirects seem to work for that. I'm trying to figure out if there's a way to get them to work, or if it's a limitation in how they function.

**Comment by vertigo220** [comment]
Figured it out, the solution is [here](https://github.com/tumpio/requestcontrol/issues/61#issuecomment-387812137).

**Comment by vertigo220** [comment]
Even though I got it working in Request Control, I'd still like to know if it's possible with Header Editor. If I can make it work with HE, I should be able to uninstall RC and reduce the # of addons I'm using. I used ^https?://www.amazon.com/gp/buy/spc/.* as the match rule, which works, but only after refreshing the page, not when landing on it.

**Comment by sylingd** [comment]
I am not an Amazon user, so when I learned about your problem, I tried to register a new account, but I can not find out what you want to do. Can you give me detailed steps?

### For example
Go to the cart, click "Proceed to checkout", the browser will redirect to `https://www.amazon.com/gp/cart/desktop/go-to-checkout.html/ref=ox_sc_proceed?isToBeGiftWrappedBefore=&proceedToCheckout=Proceed+to+checkout` and I want to redirect it to `https://www.amazon.com/gp/buy/spc/handlers/display.html?hasWorkingJavascript=1`
I used `https?://www\.amazon\.com/gp/cart/(.*?)/go-to-checkout(.*)` to `https://smile.amazon.com/gp/buy/spc/handlers/display.html` but it not work for me

**Comment by vertigo220** [comment]
That's exactly right, except for me it sends me to https://www.amazon.com/gp/buy/spc/handlers/display.html?hasWorkingJavascript=1 when I click "Proceed to checkout." But redirecting from that URL to the smile one doesn't work when clicking the checkout button, instead it still loads the www.amazon.com checkout page. But then if I refresh it, the redirect kicks in and it sends me to the Smile checkout page. Request Control works when first landing on the page, from clicking the checkout button, and doesn't require the refresh, so I was hoping HE could do that as well. I'm thinking HE is more limited in this respect and might just not work the way I want it to, in which case I'll have to stick with RC or Redirector for this and similar redirects.

**Comment by sylingd** [comment]
It works well on my browser.
![20180524135737](https://user-images.githubusercontent.com/5326684/40466966-885a12d0-5f5a-11e8-95b2-5402ad6f4500.png)

In network panel, you can see the url ` https://www.amazon.com/gp/cart/desktop/go-to-checkout.html/ref=ox_sc_proceed?proceedToCheckout=Proceed+to+checkout` is redirected to `https://smile.amazon.com/gp/buy/spc/handlers/display.html` with code "307", it means that the HE rule is in effect.
![20180524135548](https://user-images.githubusercontent.com/5326684/40467016-b64fdf30-5f5a-11e8-8761-1a3ae8a8c5eb.png)

**Comment by vertigo220** [comment]
That rule worked, though as it turns out, since Amazon has to make everything difficult, it takes three separate rules to cover all different possible conditions:

- While logged in and clicking checkout button in the actual cart: https?://www\.amazon\.com/gp/cart/(.*?)/go-to-checkout(.*)  >>  https://smile.amazon.com/gp/buy/spc/handlers/display.html
- While logged in and clicking checkout button in "cart" immediately after adding item to cart (page where it shows that you've added the item and gives you the option to go to the cart or checkout): https?://www\.amazon\.com/gp/cart/view.html/(.*?)proceedToCheckout(.*)  >>  https://smile.amazon.com/gp/buy/spc/handlers/display.html
- While not logged in (for either case/cart above): https?://www\.amazon\.com/gp/buy/signin/handlers/(.*)  >>  https://smile.amazon.com/gp/cart/desktop/go-to-checkout.html

It's possible the first two rules could be combined into one by using a wildcard (e.g. .../gp/cart/*checkout*), but I'd rather just keep it as one rule and avoid any possible unintentional consequences of doing that, not to mention I'm sick of reloading, logging out, adding to cart, going to checkout, logging in, logging out, ad nauseam. Also, the third rule doesn't work perfectly, as it actually redirects back to the cart, but on smile.amazon.com, and you have to click the checkout button again, since it seems the process of initiating checkout assigns a unique identifier which breaks the transition from amazon to amazon smile while logging in in the middle of it. While it would be nice to make it seamless and not require the additional step, it's a minor issue and one that doesn't appear fixable, since it's due to how Amazon does the checkout. Thanks for the help in figuring this out, now I need to work on my other rules.

**Comment by vertigo220** [comment]
Here's the rules for anyone that wants them:
[Header Editor - Amazon (Smile).zip](https://github.com/FirefoxBar/HeaderEditor/files/2384019/Header.Editor.-.Amazon.Smile.zip)
