### ISSUE TITLE
Tooltip when hovering over rule is cut off

### ISSUE THREAD

**Issue by vertigo220** [FirefoxBar/HeaderEditor#79]
When hovering over rules in the rule list, the tooltip only shows part of the content, cutting off the rest:

![image](https://user-images.githubusercontent.com/12024557/40501280-65e8d3a8-5f55-11e8-97cd-4a9bdd1c395d.png)

**Comment by sylingd** [comment]
A new version is under development and this issue will be fixed in the new version.
Due to the small impact of this problem, the repair version will not be released.
