### ISSUE TITLE
可否在修改的时候增加原始值的判断

### ISSUE THREAD

**Issue by smovie** [FirefoxBar/HeaderEditor#8]
比如修改Content-Type，只修改原始值是application/octet-stream为video/mp4

**Comment by sylingd** [comment]
在考虑增加自定义脚本的功能
短时间内应该不会实现

**Comment by smovie** [comment]
因为之前一直用mason，如果这个能实现的话就可以代替mason了，可以愉快的用ff57了

**Comment by sylingd** [comment]
@smovie 有计划进行，但是短期内不会实现，要考虑的东西还有点多

**Comment by sylingd** [comment]
已在最新提交中实现。将会发布新版本
