### ISSUE TITLE
Pop-up or right-click menu entry

### ISSUE THREAD

**Issue by vertigo220** [FirefoxBar/HeaderEditor#82]
Could you add either a pop-up with buttons to enable/disable all rules and to open the options/rule editor (similar to Request Control or Redirector) or add an entry to the icon's right-click menu to enable/disable all rules? Or, if doing that, better yet add entries to enable/disable all rules and to open the options, then add an option for whether clicking the icon should enable/disable all rules or open the options, so users can set it to switch it on and off when clicking the icon and, if they want to open the options to edit the rules, they can right-click and select the option from the menu.

**Comment by sylingd** [comment]
Added at [dc12f05db5c83127b524ac7018b1150d3fdb2d89](https://github.com/FirefoxBar/HeaderEditor/commit/dc12f05db5c83127b524ac7018b1150d3fdb2d89)
