### ISSUE TITLE
Modify Content-Disposition response header

### ISSUE THREAD

**Issue by vertigo220** [FirefoxBar/HeaderEditor#86]
I'm trying to get HE to change it from attachment to inline, like addons such as [Bypass Forced Download](https://addons.mozilla.org/en-US/firefox/addon/bypass-forced-download), [Inline Disposition](https://addons.mozilla.org/en-US/firefox/addon/inlinedisposition), etc. In addition, I want to make it affect only certain file types and/or sites. Here's what I have to start with (based on code provided by @earthlng for another rule):

for (let a in val) {
    if (val[a].name.toLowerCase() === 'content-disposition') { val[a].value = 'inline; filename="test.pdf"'; }
}

which will make it work regardless of if/how the header is capitalized. The first problem is that I need the filename to equal the actual name provided by the filename parameter, as opposed to "test..." Secondly, I'd like to be able to either slightly modify the code or duplicate the rule and replace a couple things to make it work for other file types, as well as maybe even make it work only on certain sites or on all but certain sites. So basically, something like this:

If (Content-Type === application/pdf OR audio/ogg OR ...) AND (domain === example.com) then change Content-Disposition to inline; filename=filename. If possible, I think it would be better to use file extension instead of MIME type, since that would allow .exe and others and would be a lot simpler than trying to find the MIME type (if it even exists) for various file types.

**Comment by sylingd** [comment]
Here are some example rules, maybe those rules can help you, if you have more questions, please continue to ask.

```
const domain = getDomain(detail.url);
// Find Content-Disposition
let cdIndex = -1;
for (let index in val) {
	if (val[a].name.toLowerCase() === 'content-disposition') {
		cdIndex = index;
		break;
	}
}
// If the original headers didn't include Content-Disposition, do nothing about this request
if (cdIndex === -1) {
	return;
}

// If domain is example.com and file extension is mp4 or flv
if (domain === "example.com" && /\.(mp4|flv)$/.test(detail.url)) {
	// Get file name like "video.mp4"
	const filename = /(\w+)\.(mp4|flv)$/.exec(detail.url)[0];
	val[cdIndex].value = 'inline; filename="' + filename + '"';
}
// If domain is not x.example.com and file extension is pdf
if (domain !== "x.example.com" && /\.pdf$/.test(detail.url)) {
	val[cdIndex].value = 'inline; filename="test.pdf"';
}
```

Note:

1. Not all website display file extension in url, for example, the Youtube video url is like that:

```
https://r6---sn-p5qs7nel.googlevideo.com/videoplayback?....
```

In this case, you can only using Content-Type to detect file type.

2. Not all urls that end with.mp4 are video, GitHub is a obvious example. 

```
https://github.com/example/example/blob/master/example.pdf
```

This is not a PDF, it is a web page.

**Comment by vertigo220** [comment]
Thanks! I understand a lot of what it's doing there, but I do have some questions:

1. At the beginning, you did "let index in val" but then kept "val[a].name.toLowerCase()". Should the [a] be changed to [index]? What's the reasoning behind the names "index" and "cdIndex?"
2. What are the "$/.test(detail.url)" and "$/.exec(detail.url)[0]" parts for?
3. How would I do multiple domains? Would I just do "if (domain === ("example.com" || "example.org" || ...) && /\.(mp4/flv)...)"?
4. How would I use Content-Type? Would it be "if (domain === "example.com" && Content-Type === "foo")"?

**Comment by sylingd** [comment]
1. My fault. I have corrected it. Because "val" is a js array, so customary we will use "index" to name the subscript.

2. `/\.(mp4|flv)$/` is a regular expression. You can press F12, open "console", and execute regular expression here. For example:
![tim 20180704135706](https://user-images.githubusercontent.com/5326684/42259243-2bd3acf8-7f92-11e8-9cf4-137bf8f94b27.png)

3. Example:
```javascript
if (domain === "google.com" || domain === "github.com" && (/\.pdf$/.test(detail.url) || /(\d+)\.mp3$/.test(detail.url))) {
	// Do something
}
```

4. Example:
```javascript
const domain = getDomain(detail.url);
// Find Content-Disposition and Content-Type
let cdIndex = -1;
let ctIndex = -1;
for (let index in val) {
	if (val[index].name.toLowerCase() === 'content-disposition') {
		cdIndex = index;
	}
	if (val[index].name.toLowerCase() === 'content-type') {
		ctIndex = index;
	}
}
// If the original headers didn't include Content-Disposition or Content-Type, do nothing about this request
if (cdIndex === -1 || ctIndex === -1) {
	return;
}

// If domain is example.com and Content-Type is application/pdf
if (domain === "example.com" && val[ctIndex].value === "application/pdf") {
	val[cdIndex].value = 'inline; filename="test.pdf"';
}
```

More documentation: [Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) [if statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else)
