### ISSUE TITLE
Remove x-frame-options from header

### ISSUE THREAD

**Issue by machsix** [FirefoxBar/HeaderEditor#87]
I tried to use the following custom function to remove 'x-frame-options' from the response header
``` javascript 
console.log('before',val);
for (let a in val) {
	if (val[a].name.toLowerCase() === 'x-frame-options') {
		  val[a] = 0;
		break;
	}
}
console.log('after',val);
```
The function seems to work for website opened in address bar as I saw logs in the console. But for website opened in iframe, I didn't see anything. Any idea?

Firefox 61.0.1

**Comment by sylingd** [comment]
Can you give me a website for test?

**Comment by machsix** [comment]
HTML code:
``` html
<html>
   <body> 
   <script language="Javascript">
   function actionCalled() {
       var iframe = document.createElement("iframe");
       iframe.id='aaa';
       iframe.src = "https://www.google.com";
       iframe.setAttribute("height", "200px");
       iframe.setAttribute("width", "400px");
       document.body.appendChild(iframe);       
  }
</script>
</body>

<button onClick="actionCalled()"> Hello Iframe !</button>
</html>
```
For Chrome with extension "Ignore X-Frame headers“， I can open google in the iframe. Thank you

**Comment by sylingd** [comment]
Try following code, it works for me
```javascript
for (let a in val) {
	if (val[a].name.toLowerCase() === 'x-frame-options') {
		val.splice(a, 1);
		break;
	}
}
```

**Comment by machsix** [comment]
I think it's a bug of the extension that it doesn't modify the reponse header for request in Iframe. With the example html I provided, google search should appear in the iframe once the button "Hello iframe" is clicked. But it didn't.

I tried another extension for firefox https://addons.mozilla.org/en-US/firefox/addon/modheader-firefox/?src=search and it works as expected.
