### ISSUE TITLE
关于规则备份、更新、与维护

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/HeaderEditor#9]
用微信公众号平台的图片反盗链简单测试了下。

- [ ] 导出的 json 不具有可读性，难以维护。

虽然可以通过编辑器来格式化，但少一步是一步嘛。

- [x] 导入规则时不检测是否是重复规则。

一个规则反复导入，在管理页面会发现不断叠加，而不是覆盖或增量修改。

- [x] 在管理页面删除规则会导致排序颠倒。

- [x] 不能对特定规则禁用。

- [ ] 需要增加测试链接，否则时间长了不知道规则是干什么的。
- [x] 建议添加在线规则订阅功能。

到57+，本扩展可能是最好的实现反盗链等功能的扩展了，非常需要在线规则来协作。

同时鉴于上述问题，在线订阅更新也便于统一用户多终端之间的管理。

https://github.com/ivysrono/URLRedirectorRules
https://github.com/ivysrono/UpgradeMixedContentBlacklist

俺已经维护了上面两个规则类项目，毫不介意再维护一个。

**Comment by sylingd** [comment]
1.导入导出功能并非用于编辑，实际上使用编辑界面修改好后再进行导出才是最合适的选择。
2.后续会优化导入功能
3.影响不大，目前暂时不打算修改
4.后续增加
5.我不认为需要，因为可以定义名称
6.能用于此扩展规则，大部分并不会像ABP、GM等扩展一样需要不断地后续更新。短时间内不会考虑

**Comment by sakuyaa** [comment]
话说可以用`JSON.stringify(result, null, '\t')`来格式化导出的json

**Comment by sylingd** [comment]
@sakuyaa 我只是认为最好不要直接修改导出的文件，导入导出功能的初衷并不是方便修改

**Comment by sylingd** [comment]
经过考虑，决定：订阅功能不会实现，但是会实现更方便的下载和导入

**Comment by sylingd** [comment]
经过考虑，决定：订阅功能不会实现，但是会实现更方便的下载和导入

**Comment by sylingd** [comment]
Added in [https://github.com/FirefoxBar/HeaderEditor/commit/7935a8511047c645f11c7dae42928f659eedfc8d](https://github.com/FirefoxBar/HeaderEditor/commit/7935a8511047c645f11c7dae42928f659eedfc8d)
