### ISSUE TITLE
暂不支持自定义函数？

### ISSUE THREAD

**Issue by waldens** [FirefoxBar/HeaderEditor#92]
有个已正常使用很久的规则，今天发现突然不能用了，我没改过HE的任何配置。请教下，什么原因？怎么解决呢？

【环境】
Win7x64  百分浏览器 v3.5.3.50（正式版本） （64 位） (portable) (Chromium 67.0.3396.99)

【重现步骤】
① 禁用全部其它扩展，只保留HE，排除无关干扰
② 匹配类型填写：`^https?://www.google.[^/]+/search\?q=tb\+(.+?)\+(.+?)&(.*)`
自定义函数：
```
out = val.replace(/^https?:\/\/www.google.[^/]+\/search\?q=tb\+(.+?)\+(.+?)&(.*)/ig, "http://tieba.baidu.com/f/search/res?ie=utf-8&kw=$1&qw=$2");
out = decodeURI(out);
return out
```
![](http://onuia4d7l.bkt.clouddn.com/2018_09_01_20180901034318.png)
③ 如上图，在测试中，粘贴入：
`https://www.google.com.hk/search?q=tb+%E9%AD%94%E5%85%BD%E4%BA%89%E9%9C%B8+%E6%9C%88%E4%BA%95%E6%AF%8F%E6%99%9A&oq=tb+%E9%AD%94%E5%85%BD%E4%BA%89%E9%9C%B8+%E6%9C%88%E4%BA%95%E6%AF%8F%E6%99%9A&aqs=chrome..69i57.451j0j9&sourceid=chrome&ie=UTF-8`

结果：以前是正常的，现在显示“暂不支持自定义函数”，实际访问也确实不能被重定向，不知道为什么

**Comment by waldens** [comment]
没事了。这个“暂不支持自定义函数”好像仅指的是，右上角的测试模块。跟实际浏览器中HE是否生效，不相关

至于实际浏览器中的重定向，刚刚突然又变正常了，不知道为什么

**Comment by gucong3000** [comment]
我也被这个文案误导了好几天，今天才发现仅仅是不支持自定义函数的预览，仅仅是不支持预览，而非不支持自定义函数，建议 @FirefoxBar 修改一下文案
