### ISSUE TITLE
冷启动后扩展似乎没有生效

### ISSUE THREAD

**Issue by lychichem** [FirefoxBar/HeaderEditor#93]
Chrome 69 x64@Win 10 x64，使用这个扩展来屏蔽谷歌的searchdomaincheck，发现每次冷启动chrome之后，写好的规则就没有生效，同时在这个扩展的管理页面显示没有规则，必须关掉窗口再开一次才行。这个有除了允许chrome后台运行之外的解决方案吗

**Comment by lychichem** [comment]
规则的写法是^https?:\/\/www\.google\.com\/searchdomaincheck.* ，正则阻止所有匹配的请求

**Comment by sylingd** [comment]
在冷启动时，会有很短一段时间读取和初始化规则（一般不超过几秒钟），这段时间所有请求都不会经过规则。但我并没有发现需要重启才能读取规则的情况

**Comment by lychichem** [comment]
我刚刚冷启动之后专门等了几秒开的管理页面（因为知道chrome的扩展加载有延迟），结果还是没显示出规则，可能跟我用的机械硬盘有关系吧，速度没你内存盘快，不过问题倒也不大，每次冷启动的时候断网就行了

**Comment by sylingd** [comment]
已经使用机械硬盘测试Chrome69，无法复现问题

**Comment by lychichem** [comment]
@sylingd 神奇，我这环境怕不是有坑，我再看看吧

**Comment by lychichem** [comment]
我发现我这边读取两条规则用了15秒以上……这什么情况……

**Comment by sylingd** [comment]
没有开启……不太清楚你的情况……
