### ISSUE TITLE
Get browsing URL

### ISSUE THREAD

**Issue by crssi** [FirefoxBar/HeaderEditor#95]
Hi

Is it possible to get the browsing URL into custom function? That is the URL in the URL/awesome bar.

Thank you

**Comment by sylingd** [comment]
This parameter needs to be obtained using extra steps, and neither browser (Chrome and Firefox) provides a synchronization API to get this content. But Chrome requires that the processing of the request must be done in a synchronous way.
In addition, in general, all CSS, JS, image, and XHR requests in a web page will carry a Referer header, and the content of this header is the URL of this webpage.

**Comment by crssi** [comment]
Cool, I haven't think of Referer approach. :+1: 

Cheers

**Comment by crssi** [comment]
Hmm. Need to test referer approach. IMHO it can collide with other extension when spoofing referer (for example Smart Referer).

**Comment by sylingd** [comment]
Yes, but so far I can't think of a better way.
