### ISSUE TITLE
建立多个分组时，重定向规则失效，且重命名分组取消后名称置空

### ISSUE THREAD

**Issue by lybtongji** [FirefoxBar/HeaderEditor#97]
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

建立了 9 个分组，刚建立时分组内的规则工作正常。但重启后重定向规则全部失效！其它规则暂未发现问题。

另外重命名分组点取消后，分组的名称会被置为 null，如下图。

![](https://i.loli.net/2018/10/21/5bcbecdc4e732.gif)

**Comment by sylingd** [comment]
这些问题已经在4.x版本中解决。请等待新版发布
