### ISSUE TITLE
4.0 导致大部分规则失效

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/HeaderEditor#98]
https://github.com/ivysrono/HeaderEditorRules/raw/master/Free.json

我已经把原来的规则删掉重新导入过了。貌似除了天涯的反盗链规则和百度文库的规则，其他的都失效了。

**Comment by sylingd** [comment]
Firefox受影响，Chrome不受影响，正在寻找原因中

**Comment by sylingd** [comment]
已修复
